Citizen.CreateThread(function()
	SwitchTrainTrack(0, true)
	SwitchTrainTrack(3, true)
	SetTrainTrackSpawnFrequency(0, 30000)
	SetTrainTrackSpawnFrequency(1, 30000)
	SetTrainTrackSpawnFrequency(2, 30000)
	SetTrainTrackSpawnFrequency(3, 30000)
	SetRandomTrains(true)
end)