RegisterServerEvent("tracker:updateTracker")
AddEventHandler("tracker:updateTracker", function(playerId, coordinates)
    local fullName = exports.character:Get(playerId, "first_name").." "..exports.character:Get(playerId, "last_name")
    TriggerClientEvent("tracker:updateTracker", -1, playerId, coordinates, fullName)
end)

RegisterServerEvent("tracker:removeTracker")
AddEventHandler("tracker:removeTracker", function(playerId)
    TriggerClientEvent("tracker:removeTracker", -1, playerId)
end)