--[[
	ANIM_FLAG_NORMAL = 0,
	ANIM_FLAG_REPEAT = 1,
	ANIM_FLAG_STOP_LAST_FRAME = 2,
	ANIM_FLAG_UPPERBODY = 16,
	ANIM_FLAG_ENABLE_PLAYER_CONTROL = 32,
	ANIM_FLAG_CANCELABLE = 120,

	Odd: loop infinitely
	Even: Freeze at last frame
	Multiple of 4: Freeze at last frame but controllable

	01 to 15 > Full body
	10 to 31 > Upper body
	32 to 47 > Full body > Controllable
	48 to 63 > Upper body > Controllable

	001 to 255 > Normal
	256 to 511 > Garbled
]]

Emotes = {
	["cancel"] = {},

	["carrybox"] = { Dict = "anim@heists@box_carry@", Name = "idle", Flag = 49, Props = {
		{ Model = "prop_cs_cardbox_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
	}, DisableCombat = true, DisableCarMovement = true, DisableJumping = true},

	["actor"] = { Dict = "special_ped@mani@monologue_7@monologue_7b", Name = "soyunactor_1", Flag = 48 },
	["actor2"] = { Dict = "special_ped@mani@monologue_7@monologue_7e", Name = "soyunactor_4", Flag = 48 },
	["actress"] = { Dict = "missmic4premiere", Name = "prem_actress_star_a", Flag = 128 },
	["aerobics"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_a", Flag = 129 },
	["aerobics2"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_b", Flag = 129 },
	["aerobics3"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_c", Flag = 129 },
	["aerobics4"] = { Dict = "timetable@tracy@ig_5@idle_b", Name = "idle_d", Flag = 129 },
	["aerobics5"] = { Dict = "timetable@tracy@ig_5@idle_b", Name = "idle_d", Flag = 129 },
	["agitated"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_a", Flag = 128 },
	["agitated2"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_b", Flag = 128 },
	["agitated3"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_c", Flag = 129 },
	["airhump"] = { Dict = "anim@mp_player_intcelebrationmale@air_shagging", Name = "air_shagging", Flag = 8 },
	["angry"] = { Dict = "switch@trevor@bridge", Name = "agressive_a", Flag = 48 },
	["angry2"] = { Dict = "switch@trevor@bridge", Name = "agressive_b", Flag = 48 },
	["argue"] = { Dict = "oddjobs@assassinate@vice@hooker", Name = "argue_a", Flag = 48 },
	["argue2"] = { Dict = "oddjobs@assassinate@vice@hooker", Name = "argue_b", Flag = 48 },
	["assure"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "average_car", Flag = 48 },
	["ballscratch"] = { Dict = "amb@code_human_in_car_mp_actions@grab_crotch@std@ds@base", Name = "idle_a" },
	["bark"] = { Dict = "random@peyote@dog", Name = "wakeup", Flag = 0 },
	["beg"] = { Dict = "oddjobs@bailbond_mountain", Name = "excited_idle_c", Flag = 48 },
	["beg2"] = { Dict = "oddjobs@bailbond_mountain", Name = "excited_idle_b", Flag = 48 },
	["berate"] = { Dict = "misscarsteal4@actor", Name = "actor_berating_assistant", Flag = 48 },
	["bigshot"] = { Dict = "special_ped@mani@monologue_8@monologue_8c", Name = "miranmemiranme_2", Flag = 48 },
	["bigshot2"] = { Dict = "special_ped@mani@monologue_8@monologue_8b", Name = "miranmemiranme_1", Flag = 48 },
	["bird"] = { Dict = "random@peyote@bird", Name = "wakeup", Flag = 48 },
	["blowkisses"] = { Dict = "anim@mp_player_intcelebrationfemale@blow_kiss", Name = "blow_kiss", Flag = 8 },
	["boi"] = { Dict = "special_ped@jane@monologue_5@monologue_5c", Name = "brotheradrianhasshown_2", Flag = 48 },
	["boobs"] = { Dict = "mini@strip_club@backroom@", Name = "stripper_b_backroom_idle_b", Flag = 8 },
	["bouncer"] = { Dict = "mini@strip_club@idles@bouncer@idle_c", Name = "idle_c", Flag = 49 },
	["bow"] = { Dict = "anim@arena@celeb@podium@no_prop@", Name = "regal_c_1st" },
	["bow2"] = { Dict = "anim@arena@celeb@podium@no_prop@", Name = "regal_a_1st" },
	["boxing"] = { Dict = "anim@mp_player_intcelebrationmale@shadow_boxing", Name = "shadow_boxing", Flag = 0 },
	["boxing2"] = { Dict = "anim@mp_player_intcelebrationfemale@shadow_boxing", Name = "shadow_boxing", Flag = 0 },
	["bringit"] = { Dict = "gestures@f@standing@casual", Name = "gesture_bring_it_on", Flag = 48 },
	["bringit2"] = { Dict = "mini@triathlon", Name = "want_some_of_this", Flag = 48 },
	["bringit3"] = { Dict = "mini@triathlon", Name = "wot_the_fuck", Flag = 48 },
	["bringiton"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bring_it_on" },
	["bringiton"] = { Dict = "misscommon@response", Name = "bring_it_on", Flag = 48 },
	["brolove"] = { Dict = "mp_player_int_upperbro_love", Name = "mp_player_int_bro_love_enter", Flag = 48 },
	["browse"] = { Dict = "amb@world_human_window_shop@male@idle_a", Name = "browse_a", Flag = 48 },
	["buttpick"] = { Dict = "friends@frt@ig_1", Name = "trevor_impatient_wait_3", Flag = 48 },
	["bye"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bye_hard" },
	["bye2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bye_soft" },
	["callover"] = { Dict = "anim@heists@prison_heistig_2_p1_exit_bus", Name = "react_a_guard_a", Flag = 48 },
	["calm"] = { Dict = "gestures@m@standing@casual", Name = "gesture_easy_now", Flag = 48 },
	["cc"] = { Dict = "amb@code_human_police_crowd_control@idle_a", Name = "idle_a", Flag = 129 },
	["cc2"] = { Dict = "amb@code_human_police_crowd_control@idle_a", Name = "idle_b", Flag = 129 },
	["cc3"] = { Dict = "amb@code_human_police_crowd_control@idle_b", Name = "idle_d", Flag = 129 },
	["celebrate"] = { Dict = "rcmfanatic1celebrate", Name = "celebrate", Flag = 48 },
	["charm"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "charm", Flag = 48 },
	["checkout"] = { Dict = "clothingspecs", Name = "try_glasses_neutral_a", Flag = 48 },
	["checkout2"] = { Dict = "clothingtrousers", Name = "check_out_a", Flag = 128 },
	["checkout3"] = { Dict = "clothingtrousers", Name = "check_out_c", Flag = 128 },
	["cheer2"] = { Dict = "amb@world_human_cheering@female_c", Name = "base", Flag = 49 },
	["cheer3"] = { Dict = "amb@world_human_cheering@female_d", Name = "base", Flag = 49 },
	["cheer4"] = { Dict = "amb@world_human_cheering@male_b", Name = "base", Flag = 49 },
	["cheer5"] = { Dict = "amb@world_human_cheering@male_a", Name = "base", Flag = 49 },
	["cheer6"] = { Dict = "random@street_race", Name = "_streetracer_accepted", Flag = 49 },
	["cheer7"] = { Dict = "mini@triathlon", Name = "male_unarmed_a", Flag = 129 },
	["cheer8"] = { Dict = "mini@triathlon", Name = "male_unarmed_b", Flag = 129 },
	["chicken"] = { Dict = "random@peyte@chickeno", Name = "wakeup", Flag = 48 },
	["chinbrush"] = { Dict = "anim@mp_player_intupperchin_brush", Name = "exit", Flag = 48 },
	["clap"] = { Dict = "amb@world_human_cheering@male_a", Name = "base", Flag = 48 },
	["clapangry"] = { Dict = "anim@arena@celeb@flat@solo@no_props@", Name = "angry_clap_a_player_a", Flag = 48 },
	["clapslow"] = { Dict = "anim@mp_player_intcelebrationmale@slow_clap", Name = "slow_clap", Flag = 48 },
	["clapslow2"] = { Dict = "anim@mp_player_intcelebrationfemale@slow_clap", Name = "slow_clap", Flag = 48 },
	["clapslow3"] = { Dict = "anim@mp_player_intupperslow_clap", Name = "idle_a", Flag = 49 },
	["clubdance"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@", Name = "hi_dance_facedj_15_v2_female^6", Flag = 1 },
	["cmon"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atad_01_g3", Flag = 48 },
	["cmon2"] = { Dict = "fra_0_int-16", Name = "ig_lamardavis-16", Flag = 48, Duration = 3000 },
	["come"] = { Dict = "gestures@m@standing@casual", Name = "gesture_come_here_hard" },
	["come2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_come_here_soft" },
	["confused"] = { Dict = "anim@amb@code_human_patrol@male@1h@idle_a", Name = "idle_a", Flag = 48 },
	["cop"] = { Dict = "amb@world_human_cop_idles@male@idle_a", Name = "idle_c", Flag = 49 },
	["count"] = { Dict = "special_ped@jane@monologue_5@monologue_5d", Name = "brotheradrianhasshown_3", Flag = 48 },
	["cower"] = { Dict = "amb@code_human_cower@male@idle_b", Name = "idle_d", Flag = 129 },
	["cower2"] = { Dict = "amb@code_human_cower@female@idle_a", Name = "idle_c", Flag = 129 },
	["cower3"] = { Dict = "amb@code_human_cower_stand@male@idle_a", Name = "idle_b", Flag = 49 },
	["cpr"] = { Dict = "missheistfbi3b_ig8_2", Name = "cpr_loop_paramedic", Flag = 1 },
	["crawl"] = { Dict = "move_injured_ground", Name = "front_loop", Flag = 1 },
	["crossarms"] = { Dict = "missheistdockssetup1showoffcar@base", Name = "base_5", Flag = 49 },
	["crossarms2"] = { Dict = "random@street_race", Name = "_car_b_lookout", Flag = 49 },
	["crossarms3"] = { Dict = "mp_corona@single_team", Name = "single_team_loop_boss", Flag = 49 },
	["crossarms4"] = { Dict = "anim@amb@nightclub@peds@", Name = "rcmme_amanda1_stand_loop_cop", Flag = 49 },
	["crossarms5"] = { Dict = "missfbi5ig_36", Name = "_idle", Flag = 49 },
	["crossarms6"] = { Dict = "random@shop_gunstore", Name = "_idle", Flag = 49 },
	["crossarms7"] = { Dict = "mini@hookers_spvanilla", Name = "idle_reject_loop_a", Flag = 49 },
	["crossroad"] = { Dict = "amb@code_human_cross_road@female@idle_a", Name = "idle_c", Flag = 129 },
	["crossroad2"] = { Dict = "amb@code_human_cross_road@male@idle_a", Name = "idle_e", Flag = 129 },
	["crotch"] = { Dict = "mp_player_int_uppergrab_crotch", Name = "mp_player_int_grab_crotch", Flag = 49 },
	["crotchdance"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_13_crotchgrab_laz", Flag = 1 },
	["cutthroat"] = { Dict = "anim@mp_player_intcelebrationfemale@cut_throat", Name = "cut_throat", Flag = 129 },
	["dab"] = { Dict = "amb@world_human_statue@base", Name = "base", Flag = 48 },
	["damn"] = { Dict = "gestures@f@standing@casual", Name = "gesture_damn", Flag = 48 },
	["damn"] = { Dict = "gestures@m@standing@casual", Name = "gesture_damn" },
	["damn2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_damn", Flag = 48 },
	["dance"] = { Dict = "anim@amb@nightclub@dancers@podium_dancers@", Name = "hi_dance_facedj_17_v2_male^5", Flag = 1 },
	["dance10"] = { Dict = "anim@mp_player_intuppercats_cradle", Name = "idle_a", Flag = 129 },
	["dance11"] = { Dict = "anim@mp_player_intupperbanging_tunes", Name = "idle_a", Flag = 129 },
	["dance12"] = { Dict = "anim@mp_player_intupperbanging_tunes_right", Name = "idle_a", Flag = 129 },
	["dance2"] = { Dict = "amb@world_human_partying@female@partying_beer@base", Name = "base", Flag = 129 },
	["dance2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "high_center_down", Flag = 1 },
	["dance3"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", Name = "high_center", Flag = 1 },
	["dance4"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "high_center_up", Flag = 1 },
	["dance5"] = { Dict = "anim@amb@casino@mini@dance@dance_solo@female@var_a@", Name = "med_center", Flag = 1 },
	["dance6"] = { Dict = "misschinese2_crystalmazemcs1_cs", "dance_loop_tao", Flag = 1 },
	["dance7"] = { Dict = "misschinese2_crystalmazemcs1_ig", "dance_loop_tao", Flag = 1 },
	["dance8"] = { Dict = "missfbi3_sniping", "dance_m_default", Flag = 1 },
	["dance9"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "med_center_up", Flag = 1 },
	["dancef"] = { Dict = "anim@amb@nightclub@dancers@solomun_entourage@", Name = "mi_dance_facedj_17_v1_female^1", Flag = 1 },
	["dancef2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center", Flag = 1 },
	["dancef3"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center_up", Flag = 1 },
	["dancef4"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^1", Flag = 1 },
	["dancef5"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^3", Flag = 1 },
	["dancef6"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center_up", Flag = 1 },
	["dancelap"] = { Dict = "mini@strip_club@private_dance@part1", Name = "priv_dance_p1", Flag = 1 },
	["dancelap2"] = { Dict = "mini@strip_club@private_dance@part2", Name = "priv_dance_p2", Flag = 1 },
	["dancelap3"] = { Dict = "mini@strip_club@private_dance@part3", Name = "priv_dance_p3", Flag = 1 },
	["dancepole"] = { Dict = "mini@strip_club@pole_dance@pole_dance1", Name = "pd_dance_01", Flag = 1 },
	["dancepole2"] = { Dict = "mini@strip_club@pole_dance@pole_dance2", Name = "pd_dance_02", Flag = 1 },
	["dancepole3"] = { Dict = "mini@strip_club@pole_dance@pole_dance3", Name = "pd_dance_03", Flag = 1 },
	["danceshy"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", Name = "low_center", Flag = 1 },
	["danceshy2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "low_center_down", Flag = 1 },
	["dancesilly"] = { Dict = "special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag", Flag = 1 },
	["dancesilly2"] = { Dict = "move_clown@p_m_zero_idles@", Name = "fidget_short_dance", Flag = 1 },
	["dancesilly3"] = { Dict = "move_clown@p_m_two_idles@", Name = "fidget_short_dance", Flag = 1 },
	["dancesilly4"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_11_buttwiggle_b_laz", Flag = 1 },
	["dancesilly5"] = { Dict = "timetable@tracy@ig_5@idle_a", "idle_a", Flag = 1 },
	["dancesilly6"] = { Dict = "timetable@tracy@ig_8@idle_b", "idle_d", Flag = 1 },
	["dancesilly7"] = { Dict = "anim@amb@casino@mini@dance@dance_solo@female@var_b@", Name = "high_center", Flag = 1 },
	["dancesilly8"] = { Dict = "anim@mp_player_intcelebrationfemale@the_woogie", "the_woogie", Flag = 1 },
	["dancesilly9"] = { Dict = "rcmnigel1bnmt_1b", "dance_loop_tyler", Flag = 1 },
	["danceslow"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "low_center", Flag = 1 },
	["danceslow2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "low_center", Flag = 1 },
	["danceslow3"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "low_center_down", Flag = 1 },
	["danceslow4"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "low_center", Flag = 1 },
	["danceupper"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "high_center", Flag = 1 },
	["danceupper2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "high_center_up", Flag = 1 },
	["dancevibe"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@", Name = "hi_dance_facedj_11_v2_male^2", Flag = 1 },
	["dazed"] = { Dict = "misscarsteal4@actor", Name = "dazed_idle", Flag = 49 },
	["dealer"] = { Dict = "amb@world_human_drug_dealer_hard@male@idle_a", Name = "idle_a", Flag = 129 },
	["dealer2"] = { Dict = "amb@world_human_drug_dealer_hard@male@idle_b", Name = "idle_d", Flag = 129 },
	["depressed"] = { Dict = "amb@world_human_bum_standing@depressed@idle_a", Name = "idle_a", Flag = 49 },
	["depressed2"] = { Dict = "oddjobs@bailbond_hobodepressed", Name = "idle_a", Flag = 49 },
	["depressed3"] = { Dict = "oddjobs@bailbond_hobodepressed", Name = "idle_c", Flag = 49 },
	["displeased"] = { Dict = "gestures@m@standing@casual", Name = "gesture_displeased" },
	["distressed"] = { Dict = "random@domestic", Name = "f_distressed_loop", Flag = 129 },
	["dj"] = { Dict = "anim@mp_player_intcelebrationfemale@dj", Name = "dj", Flag = 49 },
	["dj2"] = { Dict = "anim@mp_player_intcelebrationmale@dj", Name = "dj", Flag = 49 },
	["dj3"] = { Dict = "anim@amb@nightclub@djs@dixon@", Name = "dixn_dance_cntr_open_dix", Flag = 1 },
	["drunk"] = { Dict = "amb@world_human_bum_standing@drunk@idle_a", Name = "idle_a", Flag = 129 },
	["dustoff"] = { Dict = "reaction@shake_it_off@", Name = "dustoff", Flag = 48 },
	["dustoff2"] = { Dict = "clothingshirt", Name = "try_shirt_positive_d", Flag = 48 },
	["dustoff3"] = { Dict = "mini@racing@quad@", Name = "offroad_outro_trv", Flag = 48 },
	["easynow"] = { Dict = "gestures@m@standing@casual", Name = "gesture_easy_now" },
	["explain"] = { Dict = "special_ped@baygor@michael_1@michael_1f", Name = "hey_how_you_doing_5", Flag = 48 },
	["explain2"] = { Dict = "special_ped@baygor@michael_1@michael_1g", Name = "hey_how_you_doing_6", Flag = 48 },
	["explain3"] = { Dict = "special_ped@baygor@michael_1@michael_1h", Name = "hey_how_you_doing_7", Flag = 48 },
	["explain4"] = { Dict = "special_ped@baygor@michael_1@michael_1k", Name = "hey_how_you_doing_10", Flag = 48 },
	["explain5"] = { Dict = "special_ped@baygor@michael_2@michael_2b", Name = "hey_how_you_doing2_1", Flag = 48 },
	["explain6"] = { Dict = "special_ped@clinton@monologue_14@monologue_14b", Name = "you_know_what_they_1", Flag = 48 },
	["facepalm"] = { Dict = "anim@mp_player_intcelebrationmale@face_palm", Name = "face_palm", Flag = 48 },
	["facepalm2"] = { Dict = "anim@mp_player_intcelebrationfemale@face_palm", Name = "face_palm", Flag = 128 },
	["fail"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "fail", Flag = 48 },
	["fallover"] = { Dict = "random@drunk_driver_1", Name = "drunk_fall_over", Flag = 2 },
	["fancy"] = { Dict = "random@shop_clothes@mid", Name = "_idle_a", Flag = 129 },
	["fancy2"] = { Dict = "random@shop_clothes@mid", Name = "_idle_b", Flag = 129 },
	["fingerkiss"] = { Dict = "anim@mp_player_intupperfinger_kiss", Name = "idle_a", Flag = 48 },
	["fishdance"] = { Dict = "anim@mp_player_intupperfind_the_fish", Name = "idle_a", Flag = 129 },
	["fixtie"] = { Dict = "clothingtie", Name = "try_tie_positive_d", Flag = 48 },
	["flex2"] = { Dict = "amb@world_human_muscle_flex@arms_at_side@idle_a", Name = "idle_a", Flag = 48 },
	["flex3"] = { Dict = "amb@world_human_muscle_flex@arms_in_front@base", Name = "base", Flag = 48 },
	["flex4"] = { Dict = "amb@world_human_muscle_flex@arms_in_front@idle_a", Name = "idle_b", Flag = 48 },
	["flinch"] = { Dict = "missarmenian2", Name = "fake_punch_walk_by_lamar", Flag = 48, Duration = 2000 },
	["flip"] = { Dict = "anim@arena@celeb@flat@solo@no_props@", Name = "flip_a_player_a", Flag = 0 },
	["flipoff"] = { Dict = "mp_player_int_upperfinger", Name = "mp_player_int_finger_01_enter", Flag = 0 },
	["flipoff2"] = { Dict = "mp_player_int_upperup_yours", Name = "mp_player_int_up_yours_enter", Flag = 0 },
	["followme"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_01", Flag = 48 },
	["followme2"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_02", Flag = 48 },
	["followme3"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_03", Flag = 48 },
	["forgetit"] = { Dict = "taxi_hail", Name = "forget_it", Flag = 48 },
	["freakout"] = { Dict = "anim@mp_player_intcelebrationmale@freakout", Name = "freakout", Flag = 8 },
	["freakout2"] = { Dict = "anim@mp_player_intcelebrationfemale@freakout", Name = "freakout", Flag = 8 },
	["fu"] = { Dict = "mp_player_int_upperfinger", Name = "mp_player_int_finger_02_enter", Flag = 48 },
	["fu2"] = { Dict = "random@shop_robbery_reactions@", Name = "screw_you", Flag = 48 },
	["fyall"] = { Dict = "anim@mp_player_intcelebrationfemale@finger", Name = "finger", Flag = 48 },
	["fyall2"] = { Dict = "anim@mp_player_intupperfinger", Name = "idle_a", Flag = 48 },
	["gangidle"] = { Dict = "friends@frl@ig_1", Name = "idle_b_lamar", Flag = 129 },
	["gangidle2"] = { Dict = "misstrvram_4", Name = "thugs_idle_b", Flag = 129 },
	["gangsign"] = { Dict = "mp_player_int_uppergang_sign_a", Name = "mp_player_int_gang_sign_a", Flag = 49 },
	["gangsign2"] = { Dict = "mp_player_int_uppergang_sign_b", Name = "mp_player_int_gang_sign_b", Flag = 49 },
	["gangsign3"] = { Dict = "amb@code_human_in_car_mp_actions@gang_sign_a@std@ps@base", Name = "idle_a", Flag = 49 },
	["gangsign4"] = { Dict = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ps@base", Name = "idle_a", Flag = 49 },
	["golfswing"] = { Dict = "rcmnigel1d", Name = "swing_a_mark", Flag = 0, Duration = 4000 },
	["greet"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_1", Flag = 48 },
	["greet2"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_2", Flag = 48 },
	["greet3"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_3", Flag = 48 },
	["guitar"] = { Dict = "anim@mp_player_intcelebrationfemale@air_guitar", Name = "air_guitar", Flag = 0 },
	["handdown"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_down" },
	["handleft"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_left" },
	["handright"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_right" },
	["handshake"] = { Dict = "mp_common", Name = "givetake1_a", Flag = 0 },
	["handsonhip"] = { Dict = "timetable@amanda@ig_2", Name = "ig_2_base_amanda", Flag = 49 },
	["handsonhip2"] = { Dict = "missfbi2@leadinoutfbi_2_mcs_1", Name = "_leadin_action_fbi", Flag = 49 },
	["handsonhip3"] = { Dict = "misshair_shop@hair_dressers", Name = "keeper_idle_a", Flag = 49 },
	["handsonhip4"] = { Dict = "random@shop_tattoo", Name = "_idle", Flag = 49 },
	["handsonhip5"] = { Dict = "missfbi5leadinout", Name = "leadin_2_fra", Flag = 49 },
	["handsup"] = { Dict = "missminuteman_1ig_2", Name = "handsup_base", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["handsup2"] = { Dict = "missfra1mcs_2_crew_react", Name = "handsup_standing_base", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["handsup3"] = { Dict = "missfra1mcs_2_crew_react", Name = "idle_m_camera", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["handsup4"] = { Dict = "anim@move_hostages@female", Name = "female_idle", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["handsup5"] = { Dict = "anim@move_hostages@male", Name = "male_idle", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["handsup6"] = { Dict = "misscarsteal2chad_garage", Name = "chad_parking_garage_handsuploop_chad", Flag = 49, HandsUp = true, DisableCombat = true, DisableCarMovement = true, },
	["hangout"] = { Dict = "amb@world_human_hang_out_street@female_arm_side@idle_a", Name = "idle_a", Flag = 1 },
	["hangout2"] = { Dict = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", Name = "idle_a", Flag = 49 },
	["hangout3"] = { Dict = "amb@world_human_hang_out_street@female_hold_arm@idle_a", Name = "idle_a", Flag = 49 },
	["hangout4"] = { Dict = "amb@world_human_hang_out_street@male_a@idle_a", Name = "idle_a", Flag = 48 },
	["hangout5"] = { Dict = "amb@world_human_hang_out_street@male_b@idle_a", Name = "idle_b", Flag = 129 },
	["hangout6"] = { Dict = "amb@world_human_hang_out_street@male_c@idle_a", Name = "idle_a", Flag = 48 },
	["hangout7"] = { Dict = "oddjobs@bailbond_surf_farm", Name = "base", Flag = 129 },
	["headbutt"] = { Dict = "melee@unarmed@streamed_variations", Name = "plyr_takedown_front_headbutt", Flag = 48 },
	["hello"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello" },
	["hello"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", Flag = 48 },
	["helpme"] = { Dict = "random@bicycle_thief@ask_help", Name = "please_man_you_gotta_help_me", Flag = 48 },
	["helpme2"] = { Dict = "random@bicycle_thief@ask_help", Name = "i_cant_catch_him_on_foot", Flag = 48 },
	["highfive"] = { Dict = "mp_ped_interaction", Name = "highfive_guy_a", Flag = 0 },
	["hitch"] = { Dict = "random@hitch_lift", Name = "idle_f", Flag = 49 },
	["hitch2"] = { Dict = "random@hitch_lift", Name = "carjack_mainloop_female", Flag = 0 },
	["holster"] = { Dict = "reaction@intimidation@cop@unarmed", Name = "intro", Flag = 50 },
	["hooker"] = { Dict = "amb@world_human_prostitute@cokehead@idle_a", Name = "idle_b", Flag = 129 },
	["hooker2"] = { Dict = "amb@world_human_prostitute@crackhooker@idle_a", Name = "idle_c", Flag = 9 },
	["hug"] = { Dict = "mp_ped_interaction", Name = "kisses_guy_a", Flag = 0 },
	["huh"] = { Dict = "clothingtie", Name = "check_out_a", Flag = 48 },
	["hurry"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_b", Flag = 128 },
	["hurry2"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_e", Flag = 128 },
	["hurry3"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_f", Flag = 128 },
	["impatient"] = { Dict = "amb@world_human_stand_impatient@female@no_sign@idle_a", Name = "idle_c", Flag = 1 },
	["impatient2"] = { Dict = "amb@world_human_stand_impatient@female@no_sign@idle_a", Name = "idle_a", Flag = 49 },
	["impatient3"] = { Dict = "amb@world_human_stand_impatient@male@no_sign@idle_a", Name = "idle_a", Flag = 49 },
	["impatient4"] = { Dict = "friends@fra@ig_1", Name = "impatient_idle_a", Flag = 9 },
	["impatient5"] = { Dict = "friends@fra@ig_1", Name = "base_idle", Flag = 9 },
	["impatient6"] = { Dict = "friends@frf@ig_1", Name = "impatient_idle_c", Flag = 9 },
	["impatient7"] = { Dict = "friends@frt@ig_1", Name = "trevor_impatient_wait_1", Flag = 9 },
	["investigate"] = { Dict = "amb@world_human_guard_patrol@male@idle_b", Name = "idle_e", Flag = 128, ShowEvidence = true },
	["investigate2"] = { Dict = "amb@world_human_guard_patrol@male@idle_a", Name = "idle_a", Flag = 128, ShowEvidence = true },
	["investigate3"] = { Dict = "amb@code_human_police_investigate@idle_a", Name = "idle_a", Flag = 128, ShowEvidence = true },
	["iwill"] = { Dict = "gestures@f@standing@casual", Name = "gesture_i_will", Flag = 48 },
	["iwill"] = { Dict = "gestures@m@standing@casual", Name = "gesture_i_will" },
	["jazzhands"] = { Dict = "anim@mp_player_intcelebrationfemale@jazz_hands", Name = "jazz_hands", Flag = 48 },
	["jazzhands2"] = { Dict = "anim@mp_player_intcelebrationmale@jazz_hands", Name = "jazz_hands", Flag = 48 },
	["karate"] = { Dict = "anim@mp_player_intcelebrationfemale@karate_chops", Name = "karate_chops", Flag = 48 },
	["karate2"] = { Dict = "anim@mp_player_intcelebrationmale@karate_chops", Name = "karate_chops", Flag = 48 },
	["kc"] = { Dict = "anim@mp_player_intcelebrationfemale@knuckle_crunch", Name = "knuckle_crunch", Flag = 48 },
	["kickrocks"] = { Dict = "anim@mp_freemode_return@f@fail", Name = "fail_a", Flag = 128 },
	["knees"] = { Dict = "missprologueig_1", Name = "idle_loop_malehostage01", Flag = 129 },
	["knees2"] = { Dict = "missprologueig_2", Name = "idle_on_floor_malehostage02", Flag = 129 },
	["knockdoor"] = { Dict = "missheistfbi3b_ig7", Name = "lift_fibagent_loop", Flag = 48 },
	["lapdance"] = { Dict = "mp_am_stripper", Name = "lap_dance_girl", Flag = 1 },
	["lay"] = { Dict = "switch@trevor@annoys_sunbathers", Name = "trev_annoys_sunbathers_loop_girl", Flag = 129 },
	["lay2"] = { Dict = "switch@trevor@annoys_sunbathers", Name = "trev_annoys_sunbathers_loop_guy", Flag = 129 },
	["leanchill"] = { Dict = "amb@world_human_leaning@male@wall@back@hands_together@idle_b", Name = "idle_e", Flag = 129 },
	["leanchill2"] = { Dict = "amb@world_human_leaning@male@wall@back@legs_crossed@idle_a", Name = "idle_c", Flag = 129 },
	["leanflirt"] = { Dict = "random@street_race", Name = "_car_a_flirt_girl", Flag = 48 },
	["leanrail"] = { Dict = "missstrip_club_lean", Name = "player_lean_rail_loop", Flag = 129 },
	["leanrail2"] = { Dict = "amb@prop_human_seat_bar@male@hands_on_bar@idle_b", Name = "idle_d", Flag = 49 },
	["ledge"] = { Dict = "missfbi1", Name = "ledge_loop", Flag = 129 },
	["listen"] = { Dict = "special_ped@andy_moon@monologue_11@monologue_11e", Name = "andy_ig_1_p11_dontworrywhentheyroastyou_4", Flag = 48 },
	["lol"] = { Dict = "anim@arena@celeb@flat@paired@no_props", Name = "laugh_a_player_b", Flag = 48 },
	["lookforchange"] = { Dict = "amb@prop_human_parking_meter@male@base", Name = "base", Flag = 49 },
	["makeitrain"] = { Dict = "anim@mp_player_intupperraining_cash", Name = "idle_a_fp", Flag = 48 },
	["me"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me" },
	["me"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me", Flag = 48 },
	["me2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me_hard" },
	["me2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me_hard", Flag = 48 },
	["mechfix"] = { Dict = "anim@amb@garage@chassis_repair@", Name = "idle_01_amy_skater_01", Flag = 129 },
	["mechfix2"] = { Dict = "anim@amb@garage@chassis_repair@", Name = "idle_02_amy_skater_01", Flag = 129 },
	["mechfix3"] = { Dict = "mini@repair", Name = "fixing_a_ped", Flag = 129 },
	["mechfix4"] = { Dict = "mini@repair", Name = "fixing_a_player", Flag = 129 },
	["mechfix5"] = { Dict = "mini@repair", Name = "fixing_a_ped", Flag = 49 },
	["mechfix6"] = { Dict = "mini@repair", Name = "fixing_a_player", Flag = 49 },
	["mechfix7"] = { Dict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", Name = "machinic_loop_mechandplayer", Flag = 129 },
	["medic"] = { Dict = "amb@medic@standing@kneel@idle_a", Name = "idle_a", Flag = 1 },
	["meditate"] = { Dict = "rcmcollect_paperleadinout@", Name = "meditiate_idle", Flag = 129 },
	["meditate2"] = { Dict = "misscarsteal1leadin", Name = "devon_idle_02", Flag = 129 },
	["meditate3"] = { Dict = "mp_fm_intro_cut", Name = "base_loop", Flag = 129 },
	["middlefinger"] = { Dict = "anim@mp_player_intselfiethe_bird", Name = "idle_a", Flag = 49 },
	["mime"] = { Dict = "special_ped@mime", Name = "idle_c", Flag = 128 },
	["mindblown"] = { Dict = "anim@mp_player_intcelebrationmale@mind_blown", Name = "mind_blown", Flag = 48 },
	["mindblown2"] = { Dict = "anim@mp_player_intcelebrationfemale@mind_blown", Name = "mind_blown", Flag = 0 },
	["mine"] = { Dict = "gestures@f@standing@casual", Name = "getsure_its_mine", Flag = 48 },
	["mine"] = { Dict = "gestures@m@standing@casual", Name = "getsure_its_mine" },
	["nails"] = { Dict = "missfbi3_camcrew", Name = "final_loop_gal", Flag = 49 },
	["negative"] = { Dict = "clothingshirt", Name = "try_shirt_negative_b", Flag = 48 },
	["nervous"] = { Dict = "mp_missheist_countrybank@nervous", Name = "nervous_idle", Flag = 129 },
	["never"] = { Dict = "special_ped@andy_moon@monologue_10@monologue_10d", Name = "andy_ig_1_p10_madethemangrypraytoyour401k_3", Flag = 48 },
	["no"] = { Dict = "gestures@f@standing@casual", Name = "gesture_no_way", Flag = 48 },
	["no"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_no_hard" },
	["no2"] = { Dict = "gestures@f@standing@casual", Name = "gesture_nod_no_hard", Flag = 48 },
	["no2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_no_soft" },
	["no3"] = { Dict = "gestures@f@standing@casual", Name = "gesture_nod_no_soft", Flag = 48 },
	["no4"] = { Dict = "mini@triathlon", Name = "u_cant_do_that", Flag = 48 },
	["nod"] = { Dict = "gestures@f@standing@casual", Name = "gesture_pleased", Flag = 48 },
	["nod"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_yes_hard" },
	["nod"] = { Dict = "gestures@m@standing@casual", Name = "gesture_pleased" },
	["nope"] = { Dict = "anim@mp_player_intupperno_way", Name = "idle_a", Flag = 48 },
	["now"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_down", Flag = 48 },
	["noway"] = { Dict = "gestures@m@standing@casual", Name = "gesture_no_way" },
	["overhere"] = { Dict = "friends@frf@ig_1", Name = "over_here_idle_a", Flag = 48 },
	["overhere2"] = { Dict = "friends@frf@ig_1", Name = "over_here_idle_b", Flag = 48 },
	["overhere3"] = { Dict = "friends@frl@ig_1", Name = "waive_c_lamar", Flag = 48 },
	["passout"] = { Dict = "missarmenian2", Name = "drunk_loop", Flag = 129 },
	["passout2"] = { Dict = "random@mugging4", Name = "flee_backward_loop_shopkeeper", Flag = 129 },
	["peace"] = { Dict = "mp_player_int_upperpeace_sign", Name = "mp_player_int_peace_sign", Flag = 49 },
	["peace2"] = { Dict = "anim@mp_player_intupperpeace", Name = "idle_a", Flag = 49 },
	["peek"] = { Dict = "random@paparazzi@peek", Name = "left_peek_a", Flag = 129 },
	["peek2"] = { Dict = "anim@amb@machinery@vertical_mill@", Name = "look_high_amy_skater_01", Flag = 129 },
	["pickup"] = { Dict = "anim@am_hold_up@male", Name = "shoplift_low", Flag = 48 },
	["pickup2"] = { Dict = "random@domestic", Name = "pickup_low", Flag = 48 },
	["point"] = { Dict = "gestures@m@standing@casual", Name = "gesture_point" },
	["positive"] = { Dict = "clothingshirt", Name = "try_shirt_positive_a", Flag = 48 },
	["positive2"] = { Dict = "clothingshirt", Name = "try_shirt_positive_b", Flag = 48 },
	["praise"] = { Dict = "rcmepsilonism8", Name = "worship_base", Flag = 49 },
	["praise2"] = { Dict = "rcmepsilonism8", Name = "worship_idle_a", Flag = 49 },
	["privatedance"] = { Dict = "anim@amb@nightclub@peds@", Name = "mini_strip_club_lap_dance_ld_girl_a_song_a_p1", Flag = 1 },
	["privatedanceidle"] = { Dict = "anim@amb@nightclub@peds@", Name = "mini_strip_club_private_dance_idle_priv_dance_idle", Flag = 1 },
	["pullover"] = { Dict = "misscarsteal3pullover", Name = "pull_over_right", Flag = 48 },
	["pullups"] = { Dict = "amb@prop_human_muscle_chin_ups@male@base", Name = "base", Flag = 129 },
	["pumpdance"] = { Dict = "anim@mp_player_intupperheart_pumping", Name = "idle_a", Flag = 129 },
	["rabbit"] = { Dict = "random@peyote@rabbit", Name = "wakeup", Flag = 0 },
	["rain"] = { Dict = "amb@code_human_wander_rain@male_b@idle_a", Name = "idle_a", Flag = 49 },
	["rain2"] = { Dict = "amb@code_human_wander_rain@male_b@idle_a", Name = "idle_c", Flag = 49 },
	["raiseroof"] = { Dict = "anim@mp_player_intupperraise_the_roof", Name = "idle_a", Flag = 49 },
	["rockout"] = { Dict = "mp_player_int_upperrock", Name = "mp_player_int_rock_enter", Flag = 0 },
	["rockout2"] = { Dict = "anim@mp_player_intcelebrationmale@rock", Name = "rock", Flag = 128 },
	["rubhands"] = { Dict = "timetable@jimmy@ig_5@base", Name = "base", Flag = 48 },
	["salute"] = { Dict = "mp_player_int_uppersalute", Name = "mp_player_int_salute", Flag = 0 },
	["salute2"] = { Dict = "anim@mp_player_intcelebrationmale@salute", Name = "salute", Flag = 48 },
	["search"] = { Dict = "clothingshoes", Name = "check_out_a", Flag = 129, ShowEvidence = true },
	["search2"] = { Dict = "clothingshoes", Name = "try_shoes_positive_a", Flag = 129, ShowEvidence = true },
	["sexygrind"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_li_15_sexygrind_laz", Flag = 1 },
	["shake"] = { Dict = "gestures@m@standing@casual", Name = "gesture_head_no" },
	["shh"] = { Dict = "anim@mp_player_intuppershush", Name = "idle_a_fp", Flag = 48 },
	["shit"] = { Dict = "missfbi3ig_0", Name = "shit_loop_trev", Flag = 1 },
	["shot"] = { Dict = "random@dealgonewrong", Name = "idle_a", Flag = 129 },
	["shower"] = { Dict = "mp_safehouseshower@female@", Name = "shower_idle_a", Flag = 1 },
	["shower2"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_a", Flag = 1 },
	["shower3"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_b", Flag = 1 },
	["shower4"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_c", Flag = 1 },
	["shower5"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_d", Flag = 1 },
	["shrug"] = { Dict = "gestures@f@standing@casual", Name = "gesture_shrug_hard", Flag = 48 },
	["shrug"] = { Dict = "gestures@m@standing@casual", Name = "gesture_shrug_hard" },
	["shrug2"] = { Dict = "gestures@f@standing@casual", Name = "gesture_shrug_soft", Flag = 48 },
	["shrug2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_shrug_soft" },
	["shrug3"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_afac_01_g1", Flag = 48 },
	["sit1"] = { Dict = "anim@amb@business@bgen@bgen_no_work@", Name = "sit_phone_phoneputdown_idle_nowork", Flag = 1 },
	["sit2"] = { Dict = "rcm_barry3", Name = "barry_3_sit_loop", Flag = 1 },
	["sit3"] = { Dict = "amb@world_human_picnic@male@idle_a", Name = "idle_a", Flag = 1 },
	["sit4"] = { Dict = "amb@world_human_picnic@female@base", Name = "base", Flag = 1 },
	["sit5"] = { Dict = "anim@heists@fleeca_bank@ig_7_jetski_owner", Name = "owner_idle", Flag = 1 },
	["sit6"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "idle_a_jimmy", Flag = 1 },
	["sit7"] = { Dict = "anim@amb@nightclub@lazlow@lo_alone@", Name = "lowalone_base_laz", Flag = 1 },
	["sit8"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "mics3_15_base_jimmy", Flag = 1 },
	["sit9"] = { Dict = "amb@world_human_stupor@male@idle_a", Name = "idle_a", Flag = 1 },
	["sitchair2"] = { Dict = "timetable@ron@ig_5_p3", Name = "ig_5_p3_base", Flag = 1 },
	["sitchair3"] = { Dict = "timetable@reunited@ig_10", Name = "base_amanda", Flag = 1 },
	["sitchair4"] = { Dict = "timetable@ron@ig_3_couch", Name = "base", Flag = 1 },
	["sitchair5"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "mics3_15_base_tracy", Flag = 1 },
	["sitchair6"] = { Dict = "timetable@maid@couch@", Name = "base", Flag = 1 },
	["sitchairside"] = { Dict = "timetable@ron@ron_ig_2_alt1", Name = "ig_2_alt1_base", Flag = 1 },
	["sitdrunk"] = { Dict = "timetable@amanda@drunk@base", Name = "base", Flag = 1 },
	["sitlean"] = { Dict = "timetable@tracy@ig_14@", Name = "ig_14_base_tracy", Flag = 1 },
	["sitsad"] = { Dict = "anim@amb@business@bgen@bgen_no_work@", Name = "sit_phone_phoneputdown_sleeping-noworkfemale", Flag = 1 },
	["sitscared"] = { Dict = "anim@heists@ornate_bank@hostages@hit", Name = "hit_loop_ped_b", Flag = 1 },
	["sitscared2"] = { Dict = "anim@heists@ornate_bank@hostages@ped_c@", Name = "flinch_loop", Flag = 1 },
	["sitscared3"] = { Dict = "anim@heists@ornate_bank@hostages@ped_e@", Name = "flinch_loop", Flag = 1 },
	["sleepwalk"] = { Dict = "mp_sleep", Name = "sleep_loop", Flag = 49 },
	["slowclap2"] = { Dict = "anim@mp_player_intcelebrationfemale@slow_clap", Name = "slow_clap", Flag = 48 },
	["slowclap3"] = { Dict = "anim@mp_player_intcelebrationmale@slow_clap", Name = "slow_clap", Flag = 48 },
	["slumped2"] = { Dict = "amb@world_human_bum_slumped@male@laying_on_right_side@idle_a", Name = "idle_a", Flag = 129 },
	["smackthat"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_17_smackthat_laz", Flag = 1 },
	["smell"] = { Dict = "move_p_m_two_idles@generic", Name = "fidget_sniff_fingers", Flag = 49, Duration = 4000 },
	["smh"] = { Dict = "gestures@m@standing@casual", Name = "gesture_head_no", Flag = 48 },
	["spiderdance"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_17_spiderman_laz", Flag = 1 },
	["spiderman"] = { Dict = "missexile3", Name = "ex03_train_roof_idle", Flag = 48 },
	["standingjog"] = { Dict = "amb@world_human_jog_standing@female@idle_a", Name = "idle_a", Flag = 129 },
	["standingjog2"] = { Dict = "amb@world_human_jog_standing@male@fitidle_a", Name = "idle_a", Flag = 129 },
	["steeple"] = { Dict = "ep_8_rcm-2", Name = "cs_chrisformage_dual-2", Flag = 48, BlendIn = 1.0, BlendOut = 1.0 },
	["stink"] = { Dict = "anim@mp_player_intcelebrationfemale@stinker", Name = "stinker", Flag = 48 },
	["stretch"] = { Dict = "switch@franklin@press_ups", Name = "stretch_long", Flag = 48 },
	["stretch2"] = { Dict = "switch@franklin@press_ups", Name = "stretch_short", Flag = 48 },
	["stretch3"] = { Dict = "switch@franklin@bed", Name = "stretch_short", Flag = 48 },
	["suicide"] = { Dict = "mp_suicide", Name = "pistol", Flag = 0 },
	["sunbathe3"] = { Dict = "amb@world_human_sunbathe@female@front@idle_a", Name = "idle_c", Flag = 129 },
	["sunbathe4"] = { Dict = "amb@world_human_sunbathe@male@front@idle_a", Name = "idle_a", Flag = 129 },
	["superhero"] = { Dict = "rcmbarry", Name = "base", Flag = 129 },
	["swatback"] = { Dict = "swat", Name = "you_back", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatcome"] = { Dict = "swat", Name = "come", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatforward"] = { Dict = "swat", Name = "you_fwd", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatfreeze"] = { Dict = "swat", Name = "freeze", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatgo"] = { Dict = "swat", Name = "go_fwd", Flag = 48, BlendOut = 1.5, Duration = 1500 },
	["swatleft"] = { Dict = "swat", Name = "you_left", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatokay"] = { Dict = "swat", Name = "understood", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatrally"] = { Dict = "swat", Name = "rally_point", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["swatright"] = { Dict = "swat", Name = "you_right", Flag = 48, BlendOut = 1.5, Duration = 1000 },
	["t"] = { Dict = "nm@hands", Name = "hands_up", Flag = 49 },
	["tap"] = { Dict = "gestures@miss@fra_0", Name = "lamar_fkn0_cjae_01_g4", Flag = 48 },
	["taunt"] = { Dict = "switch@franklin@gang_taunt_p1", Name = "gang_taunt_loop_lamar", Flag = 48 },
	["taunt2"] = { Dict = "switch@franklin@gang_taunt_p1", Name = "gang_taunt_loop_thug_02", Flag = 48 },
	["taunt3"] = { Dict = "switch@franklin@gang_taunt_p3", Name = "gang_taunt_with_lamar_loop_lamar", Flag = 48 },
	["taunt4"] = { Dict = "switch@franklin@gang_taunt_p5", Name = "fras_ig_6_p5_loop_lamar", Flag = 48 },
	["taxi"] = { Dict = "taxi_hail", Name = "hail_taxi", Flag = 48 },
	["teapotdance"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_mi_17_teapotthrust_laz", Flag = 1 },
	["thanks"] = { Dict = "random@thanks", Name = "thanks_ps", Flag = 48 },
	["thanks2"] = { Dict = "random@arrests", Name = "thanks_male_05", Flag = 48 },
	["thehand"] = { Dict = "mini@prostitutestalk", Name = "street_argue_f_a", Flag = 8 },
	["there"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_asab_01_g2", Flag = 48 },
	["there2"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atab_01_g2", Flag = 48 },
	["think"] = { Dict = "mp_cp_stolen_tut", Name = "b_think", Flag = 48 },
	["thinking"] = { Dict = "misscarsteal4@aliens", Name = "rehearsal_base_idle_director", Flag = 49 },
	["thinking2"] = { Dict = "mini@hookers_spcokehead", Name = "idle_wait", Flag = 49 },
	["thinking3"] = { Dict = "anim_casino_a@amb@casino@games@spectate@cardtable@ped_male@stand@01a@base", Name = "base", Flag = 49 },
	["thinking4"] = { Dict = "anim@amb@casino@hangout@ped_male@stand@02b@idles", Name = "idle_a", Flag = 49 },
	["thumbsup"] = { Dict = "anim@mp_player_intcelebrationfemale@thumbs_up", Name = "thumbs_up", Flag = 48 },
	["thumbsup"] = { Dict = "anim@mp_player_intselfiethumbs_up", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["thumbsup2"] = { Dict = "anim@mp_player_intupperthumbs_up", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["thumbsup2"] = { Dict = "random@shop_clothes@low", Name = "_reaction_a", Flag = 48 },
	["thumbsup3"] = { Dict = "anim@mp_player_intincarthumbs_upstd@ds@", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["thumbsup3"] = { Dict = "anim@mp_player_intupperthumbs_up", Name = "idle_a_fp", Flag = 48 },
	["thumbsup4"] = { Dict = "anim@mp_player_intincarthumbs_upstd@ps@", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["thumbsup5"] = { Dict = "anim@mp_player_intincarthumbs_upstd@rds@", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["thumbsup6"] = { Dict = "anim@mp_player_intincarthumbs_upstd@rps@", Name = "idle_a", Flag = 49, Blend = 2.0 },
	["time"] = { Dict = "friends@frm@ig_1", Name = "greeting_idle_b", Flag = 48 },
	["timid"] = { Dict = "missfam6ig_7_tattoo", Name = "ig_7_idle_02_tracey", Flag = 129 },
	["tough"] = { Dict = "missbigscore1", Name = "idle_d", Flag = 129 },
	["tough2"] = { Dict = "missbigscore1", Name = "idle_e", Flag = 129 },
	["tough3"] = { Dict = "random@shop_gunstore", Name = "_idle_a", Flag = 129 },
	["tough4"] = { Dict = "random@shop_gunstore", Name = "_idle_b", Flag = 129 },
	["tourguide"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_a", Flag = 128 },
	["tourguide2"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_b", Flag = 128 },
	["tourguide3"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_c", Flag = 8 },
	["traffic"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_a", Flag = 49 },
	["traffic2"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_c", Flag = 49 },
	["traffic3"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_e", Flag = 49 },
	["turnaround"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_11_turnaround_laz", Flag = 1 },
	["twerk"] = { Dict = "switch@trevor@mocks_lapdance", Name = "001443_01_trvs_28_idle_stripper", Flag = 129 },
	["twitchy"] = { Dict = "amb@world_human_bum_standing@twitchy@idle_a", Name = "idle_a", Flag = 49 },
	["twitchy2"] = { Dict = "oddjobs@bailbond_hobotwitchy", Name = "idle_b", Flag = 49 },
	["typing"] = { Dict = "mp_fib_grab", Name = "loop", Flag = 49 },
	["vsign"] = { Dict = "mp_player_int_upperv_sign", Name = "mp_player_int_v_sign", Flag = 49 },
	["wank"] = { Dict = "mp_player_int_upperwank", Name = "mp_player_int_wank_01", Flag = 0 },
	["wary"] = { Dict = "mp_am_hold_up", Name = "wary_loop", Flag = 129 },
	["wave"] = { Dict = "friends@frj@ig_1", Name = "wave_a", BlendOut = 1.0 },
	["wave"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", Flag = 0 },
	["wave2"] = { Dict = "friends@frj@ig_1", Name = "wave_b", Flag = 48 },
	["wave2"] = { Dict = "random@mugging5", Name = "001445_01_gangintimidation_1_female_idle_b", BlendOut = 1.0 },
	["wave3"] = { Dict = "friends@frj@ig_1", Name = "wave_b", BlendOut = 1.0 },
	["wave3"] = { Dict = "friends@frj@ig_1", Name = "wave_d", Flag = 48 },
	["wave4"] = { Dict = "friends@frj@ig_1", Name = "wave_e", BlendOut = 1.0 },
	["wave4"] = { Dict = "friends@frj@ig_1", Name = "wave_e", Flag = 48 },
	["wave5"] = { Dict = "random@gang_intimidation@", Name = "001445_01_gangintimidation_1_female_wave_loop", Flag = 49 },
	["wavecrowd"] = { Dict = "anim@mp_player_intcelebrationfemale@wave", Name = "wave", BlendOut = 1.0 },
	["wavehey"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", BlendOut = 1.0 },
	["waveme"] = { Dict = "friends@frj@ig_1", Name = "wave_c", BlendOut = 1.0 },
	["waveno"] = { Dict = "friends@frj@ig_1", Name = "wave_d", BlendOut = 1.0 },
	["wavesassy"] = { Dict = "friends@fra@ig_1", Name = "over_here_idle_a", BlendOut = 1.0 },
	["what"] = { Dict = "gestures@f@standing@casual", Name = "gesture_what_hard", Flag = 48 },
	["what"] = { Dict = "gestures@m@standing@casual", Name = "gesture_what_hard" },
	["what2"] = { Dict = "gestures@f@standing@casual", Name = "gesture_what_soft", Flag = 48 },
	["what2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_what_soft" },
	["what3"] = { Dict = "special_ped@baygor@monologue_1@monologue_1e", Name = "ask_you_a_question_4", Flag = 48 },
	["whatup"] = { Dict = "mp_intro_seq@ig_4_car_select@", Name = "idle_c_lamar", Flag = 48 },
	["whatup2"] = { Dict = "friends@frl@ig_1", Name = "waive_a_lamar", Flag = 48 },
	["whatup3"] = { Dict = "mp_intro_seq@ig_4_car_select@", Name = "idle_d_lamar", Flag = 48 },
	["whocares"] = { Dict = "anim@mp_celebration@draw@female", Name = "draw_react_female_b", Flag = 128 },
	["whocares2"] = { Dict = "anim@mp_celebration@draw@male", Name = "draw_react_male_b", Flag = 128 },
	["why"] = { Dict = "gestures@m@standing@casual", Name = "gesture_why" },
	["why"] = { Dict = "random@shop_robbery_reactions@", Name = "but_why", Flag = 48 },
	["why2"] = { Dict = "gestures@f@standing@casual", Name = "gesture_why", Flag = 48 },
	["why2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_why_left" },
	["why3"] = { Dict = "random@shop_robbery_reactions@", Name = "shock", Flag = 48 },
	["writhe"] = { Dict = "combat@damage@rb_writhe", Name = "rb_writhe_loop", Flag = 129 },
	["writhe2"] = { Dict = "combat@damage@writheidle_a", Name = "writhe_idle_a", Flag = 129 },
	["writhe3"] = { Dict = "random@dealgonewrong", Name = "idle_a", Flag = 129 },
	["writhe4"] = { Dict = "random@dealgonewrong", Name = "idle_b", Flag = 129 },
	["wtf"] = { Dict = "misscommon@response", Name = "numbnuts", Flag = 48 },
	["yes"] = { Dict = "gestures@f@standing@casual", Name = "gesture_nod_yes_hard", Flag = 48 },
	["yes"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_yes_hard" },
	["yes2"] = { Dict = "gestures@f@standing@casual", Name = "gesture_nod_yes_soft", Flag = 48 },
	["yes2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_yes_soft" },
	["yo"] = { Dict = "arm_1_mcs_2_concat-2", Name = "cs_lamardavis_dual-2", Flag = 48, BlendOut = 1.4, Duration = 600 },
	["yoga2"] = { Dict = "amb@world_human_yoga@female@base", Name = "base_c", Flag = 129 },
	["yoga3"] = { Dict = "timetable@amanda@ig_4", Name = "ig_4_idle", Flag = 129 },
	["you"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_hard" },
	["you"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_hard", Flag = 48 },
	["you2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_soft" },
	["you2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_soft", Flag = 48 },

	["danceglowstick"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_13_mi_hi_sexualgriding_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_glowstick_01", Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }},
		{ Model = "ba_prop_battle_glowstick_01", Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }},
	}},
	["danceglowstick2"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_12_mi_hi_bootyshake_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_glowstick_01", Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }},
		{ Model = "ba_prop_battle_glowstick_01", Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }},
	}},
	["danceglowstick3"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_09_mi_hi_bellydancer_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_glowstick_01", Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }},
		{ Model = "ba_prop_battle_glowstick_01", Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }},
	}},
	["dancehorse"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_15_handup_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_hobby_horse", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
	}},
	["dancehorse2"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_hi_11_handup_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_hobby_horse", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
	}},
	["dancehorse3"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_11_hu_shimmy_laz", Flag = 1, Props = {
		{ Model = "ba_prop_battle_hobby_horse", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
	}},
	["map2"] = { Dict = "amb@world_human_tourist_map@female@idle_a", Name = "idle_a", "Map", Flag = 49, Props = {
		{ Model = "prop_tourist_map_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
	}},
	["tablet"] = { Dict = "amb@code_human_in_bus_passenger_idles@female@tablet@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_cs_tablet", Bone = 60309, Offset = { 0.03, 0.002, 0.0, 10.0, -20.0, 0.0 }},
	}},
	["umbrella"] = { Dict = "amb@world_human_drinking@coffee@male@base", Name = "base", Flag = 49, Props = {
		{ Model = "p_amb_brolly_01", Bone = 57005, Offset = { 0.15, 0.005, 0.0, 87.0, -20.0, 180.0 } },
	}},
	["notepad"] = { Dict = "missheistdockssetup1clipboard@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_notepad_01", Bone = 18905, Offset = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
		{ Model = "prop_pencil_01", Bone = 58866, Offset = {  0.11, -0.02, 0.001, -120.0, 0.0, 0.0  } },
	}},
	["rose"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
		{ Model = "prop_single_rose", Bone = 18905, Offset = { 0.13, 0.15, 0.0, -100.0, 0.0, -20.0 } },
	}},
	["suitcase"] = { Dict = "missheistdocksprep1hold_cellphone", Name = "static", Flag = 49, Props = {
		{ Model = "prop_ld_suitcase_01", Bone = 57005, Offset = { 0.39, 0.0, 0.0, 0.0, 266.0, 60.0 } },
	}},
	["suitcase2"] = { Dict = "missheistdocksprep1hold_cellphone", Name = "static", Flag = 49, Props = {
		{ Model = "prop_security_case_01", Bone = 57005, Offset = { 0.10, 0.0, 0.0, 0.0, 280.0, 53.0 } },
	}},
	["mugshot"] = { Dict = "mp_character_creation@customise@male_a", Name = "loop", Flag = 49, Props = {
		{ Model = "prop_police_id_board", Bone = 58868, Offset = { 0.12, 0.24, 0.0, 5.0, 0.0, 70.0 } },
	}},
	["coffee"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
		{ Model = "p_amb_coffeecup_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["whiskey"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
		{ Model = "prop_drink_whisky", Bone = 28422, Offset = { 0.01, -0.01, -0.06, 0.0, 0.0, 0.0 } },
	}},
	["beer"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
		{ Model = "prop_amb_beer_bottle", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["cup"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
		{ Model = "prop_plastic_cup_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["donut"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
		{ Model = "prop_amb_donut", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
	}},
	["burger"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
		{ Model = "prop_cs_burger_01", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
	}},
	["sandwich"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
		{ Model = "prop_sandwich_01", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
	}},
	["soda"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
		{ Model = "prop_ecola_can", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 130.0 } },
	}},
	["egobar"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
		{ Model = "prop_choc_ego", Bone = 60309, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["wine"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
		{ Model = "prop_drink_redwine", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
	}},
	["flute"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
		{ Model = "prop_champ_flute", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
	}},
	["champagne"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
		{ Model = "prop_drink_champ", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
	}},
	["guitar"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
		{ Model = "prop_acc_guitar_01", Bone = 24818, Offset = { -0.1, 0.31, 0.1, 10.0, -20.0, 150.0 } },
	}},
	["guitar2"] = { Dict = "switch@trevor@guitar_beatdown", Name = "001370_02_trvs_8_guitar_beatdown_idle_busker", Flag = 49, Props = {
		{ Model = "prop_acc_guitar_01", Bone = 24818, Offset = { -0.05, 0.31, 0.1, 10.0, -20.0, 150.0 } },
	}},
	["guitarelectric"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
		{ Model = "prop_el_guitar_01", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
	}},
	["guitarelectric2"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
		{ Model = "prop_el_guitar_02", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
	}},
	["guitarelectric3"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
		{ Model = "prop_el_guitar_03", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
	}},
	["book"] = { Dict = "cellphone@", Name = "cellphone_text_read_base", Flag = 49, Props = {
		{ Model = "prop_novel_01", Bone = 6286, Offset = { 0.15, 0.03, -0.055, 0.0, 180.0, -90.0 } },
	}},
	["bouquet"] = { Dict = "impexp_int-0", Name = "mp_m_waremech_01_dual-0", Flag = 49, Props = {
		{ Model = "prop_snow_flower_02", Bone = 24817, Offset = { -0.29, 0.40, -0.02, -90.0, -90.0, 0.0 } },
	}},
	["teddy"] = { Dict = "impexp_int-0", Name = "mp_m_waremech_01_dual-0", Flag = 49, Props = {
		{ Model = "v_ilev_mr_rasberryclean", Bone = 24817, Offset = { -0.20, 0.46, -0.016, -180.0, -90.0, 0.0 } },
	}},
	["backpack"] = { Dict = "move_p_m_zero_rucksack", Name = "idle", Flag = 49, Props = {
		{ Model = "p_michael_backpack_s", Bone = 24818, Offset = { 0.07, -0.11, -0.05, 0.0, -90.0, 175.0 } },
	}},
	["clipboard"] = { Dict = "missfam4", Name = "base", Flag = 49, Props = {
		{ Model = "p_amb_clipboard_01", Bone = 36029, Offset = { 0.16, 0.08, 0.1, -130.0, -50.0, 0.0 } },
	}},
	["map"] = { Dict = "amb@world_human_tourist_map@male@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_tourist_map_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["beg"] = { Dict = "amb@world_human_bum_freeway@male@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_beggers_sign_03", Bone = 58868, Offset = { 0.19, 0.18, 0.0, 5.0, 0.0, 40.0 } },
	}},
	["makeitrain"] = { Dict = "anim@mp_player_intupperraining_cash", Name = "idle_a", Flag = 49, Props = {
		{ Model = "prop_anim_cash_pile_01", Bone = 60309, Offset = { 0.0, 0.0, 0.0, 180.0, 0.0, 70.0 } },
	}},
	["camera"] = { Dict = "amb@world_human_paparazzi@male@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_pap_camera_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}, ShowEvidence = true },
	["champagnespray"] = { Dict = "anim@mp_player_intupperspray_champagne", Name = "idle_a", Flag = 49, Props = {
		{ Model = "ba_prop_battle_champ_open", Bone = 28422, Offset = { 0.0,0.0,0.0,0.0,0.0,0.0 } },
	}},
	["phonecall"] = { Dict = "cellphone@", Name = "cellphone_call_listen_base", Flag = 49, Props = {
		{ Model = "prop_npc_phone_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["phone"] = { Dict = "cellphone@", Name = "cellphone_text_read_base", Flag = 49, Props = {
		{ Model = "prop_npc_phone_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
	}},
	["clean"] = { Dict = "timetable@floyd@clean_kitchen@base", Name = "base", Flag = 49, Props = {
		{ Model = "prop_sponge_01", Bone = 28422, Offset = { 0.0, 0.0, -0.01, 90.0, 0.0, 0.0 } },
	}},
	["clean2"] = { Dict = "amb@world_human_maid_clean@", Name = "base", Flag = 49, Props = {
		{ Model = "prop_sponge_01", Bone = 28422, Offset = { 0.0, 0.0, -0.01, 90.0, 0.0, 0.0 } },
	}},

	["bbq"] = { Scenario = "PROP_HUMAN_BBQ", PlayEnterAnim = true },
	["beer"] = { Scenario = "WORLD_HUMAN_PARTYING", PlayEnterAnim = true },
	["cheer"] = { Scenario = "WORLD_HUMAN_CHEERING", PlayEnterAnim = true },
	["coffee2"] = { Scenario = "WORLD_HUMAN_AA_COFFEE", PlayEnterAnim = true },
	["cpa"] = { Scenario = "WORLD_HUMAN_CAR_PARK_ATTENDANT", PlayEnterAnim = true },
	["dance"] = { Scenario = "WORLD_HUMAN_STRIP_WATCH_STAND", PlayEnterAnim = true },
	["drink"] = { Scenario = "WORLD_HUMAN_DRINKING", PlayEnterAnim = true },
	["film"] = { Scenario = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", PlayEnterAnim = true },
	["firebum"] = { Scenario = "WORLD_HUMAN_STAND_FIRE", PlayEnterAnim = true },
	["fishing"] = { Scenario = "WORLD_HUMAN_STAND_FISHING", PlayEnterAnim = true },
	["flex"] = { Scenario = "WORLD_HUMAN_MUSCLE_FLEX", PlayEnterAnim = true },
	["freewaybum"] = { Scenario = "WORLD_HUMAN_BUM_FREEWAY", PlayEnterAnim = true },
	["garbagebum"] = { Scenario = "PROP_HUMAN_BUM_BIN", PlayEnterAnim = true },
	["gardener"] = { Scenario = "WORLD_HUMAN_GARDENER_PLANT", PlayEnterAnim = true },
	["hammer"] = { Scenario = "WORLD_HUMAN_HAMMERING", PlayEnterAnim = true },
	["janitor"] = { Scenario = "WORLD_HUMAN_JANITOR", PlayEnterAnim = true },
	["joginplace"] = { Scenario = "WORLD_HUMAN_JOG_STANDING", PlayEnterAnim = true },
	["leafblower"] = { Scenario = "WORLD_HUMAN_GARDENER_LEAF_BLOWER", PlayEnterAnim = true },
	["lean"] = { Scenario = "WORLD_HUMAN_LEANING", PlayEnterAnim = true },
	["lean2"] = { Scenario = "PROP_HUMAN_BUM_SHOPPING_CART", PlayEnterAnim = true },
	["map"] = { Scenario = "WORLD_HUMAN_TOURIST_MAP", PlayEnterAnim = true },
	["musician"] = { Scenario = "WORLD_HUMAN_MUSICIAN", PlayEnterAnim = true },
	["paparazzi"] = { Scenario = "WORLD_HUMAN_PAPARAZZI", PlayEnterAnim = true },
	["prostitute"] = { Scenario = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", PlayEnterAnim = true },
	["prostitute2"] = { Scenario = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", PlayEnterAnim = true },
	["pushups"] = { Scenario = "WORLD_HUMAN_PUSH_UPS", PlayEnterAnim = true },
	["sitchair"] = { Scenario = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", Sit = true, Offset = vector4(0.0, -0.7, -0.45, 0.0) },
	["slumped"] = { Scenario = "WORLD_HUMAN_BUM_SLUMPED", PlayEnterAnim = true },
	["statue"] = { Scenario = "WORLD_HUMAN_HUMAN_STATUE", PlayEnterAnim = true },
	["sunbathe"] = { Scenario = "WORLD_HUMAN_SUNBATHE", PlayEnterAnim = true },
	["sunbathe2"] = { Scenario = "WORLD_HUMAN_SUNBATHE_BACK", PlayEnterAnim = true },
	["tennis"] = { Scenario = "WORLD_HUMAN_TENNIS_PLAYER", PlayEnterAnim = true },
	["torch"] = { Scenario = "WORLD_HUMAN_SECURITY_SHINE_TORCH", PlayEnterAnim = true },
	["tourist"] = { Scenario = "WORLD_HUMAN_TOURIST_MOBILE", PlayEnterAnim = true },
	["wash"] = { Scenario = "WORLD_HUMAN_BUM_WASH", PlayEnterAnim = true },
	["weights"] = { Scenario = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", PlayEnterAnim = true },
	["yoga"] = { Scenario = "WORLD_HUMAN_YOGA", PlayEnterAnim = true },
	["mobile"] = { Scenario = "WORLD_HUMAN_STAND_MOBILE", PlayEnterAnim = true },
	["weld"] = { Scenario = "WORLD_HUMAN_WELDING", PlayEnterAnim = true },

	["situps"] = { Sequence = {
		{ Dict = "amb@world_human_sit_ups@male@enter", Name = "enter", Flag = 0 },
		{ Dict = "amb@world_human_sit_ups@male@idle_a", Name = "idle_a", Flag = 1 },
	}},

	["situps2"] = { Sequence = {
		{ Dict = "amb@world_human_sit_ups@male@enter", Name = "enter", Flag = 0 },
		{ Dict = "amb@world_human_sit_ups@male@idle_a", Name = "idle_c", Flag = 1 },
	}},
}

Walkstyles = {
	["reset"] = {},
	["alien"] = { Name = "move_m@alien" },
	["armored"] = { Name = "anim_group_move_ballistic" },
	["arrogant"] = { Name = "move_f@arrogant@a" },
	["brave"] = { Name = "move_m@brave" },
	["casual"] = { Name = "move_m@casual@a" },
	["casual2"] = { Name = "move_m@casual@b" },
	["casual3"] = { Name = "move_m@casual@c" },
	["casual4"] = { Name = "move_m@casual@d" },
	["casual5"] = { Name = "move_m@casual@e" },
	["casual6"] = { Name = "move_m@casual@f" },
	["chichi"] = { Name = "move_f@chichi" },
	["confident"] = { Name = "move_m@confident" },
	["cop"] = { Name = "move_m@business@a" },
	["cop2"] = { Name = "move_m@business@b" },
	["cop3"] = { Name = "move_m@business@c" },
	["depressed"] = { Name = "move_m@depressed@a" },
	["drunk"] = { Name = "move_m@drunk@slightlydrunk" },
	["drunk2"] = { Name = "move_m@drunk@moderatedrunk" },
	["drunk3"] = { Name = "move_m@drunk@verydrunk" },
	["fat"] = { Name = "move_m@fat@a" },
	["female"] = { Name = "move_f@multiplayer" },
	["femme"] = { Name = "move_f@femme@" },
	["fire"] = { Name = "move_characters@franklin@fire" },
	["fire2"] = { Name = "move_characters@michael@fire" },
	["fire3"] = { Name = "move_m@fire" },
	["flee"] = { Name = "move_f@flee@a" },
	["franklin"] = { Name = "move_p_m_one" },
	["gangster"] = { Name = "move_m@gangster@generic" },
	["gangster2"] = { Name = "move_m@gangster@ng" },
	["gangster3"] = { Name = "move_m@gangster@var_e" },
	["gangster4"] = { Name = "move_m@gangster@var_f" },
	["gangster5"] = { Name = "move_m@gangster@var_i" },
	["golfer"] = { Name = "move_m@golfer@ " },
	["grooving"] = { Name = "anim@move_m@grooving@" },
	["guard"] = { Name = "move_m@prison_gaurd" },
	["handcuffs"] = { Name = "move_m@prisoner_cuffed" },
	["heels"] = { Name = "move_f@heels@c" },
	["heels2"] = { Name = "move_f@heels@d" },
	["hiking"] = { Name = "move_m@hiking" },
	["hipster"] = { Name = "move_m@hipster@a" },
	["hobo"] = { Name = "move_m@hobo@a" },
	["hurry"] = { Name = "move_f@hurry@a" },
	["injured"] = { Name = "move_m@injured" },
	["janitor"] = { Name = "move_p_m_zero_janitor" },
	["janitor2"] = { Name = "move_p_m_zero_slow" },
	["jog"] = { Name = "move_m@jog@" },
	["lemar"] = { Name = "anim_group_move_lemar_alley" },
	["lester"] = { Name = "move_heist_lester" },
	["lester2"] = { Name = "move_lester_caneup" },
	["male"] = { Name = "move_m@multiplayer" },
	["maneater"] = { Name = "move_f@maneater" },
	["michael"] = { Name = "move_ped_bucket" },
	["money"] = { Name = "move_m@money" },
	["muscle"] = { Name = "move_m@muscle@a" },
	["posh"] = { Name = "move_m@posh@" },
	["posh2"] = { Name = "move_f@posh@" },
	["quick"] = { Name = "move_m@quick" },
	["runner"] = { Name = "female_fast_runner" },
	["sad"] = { Name = "move_m@sad@a" },
	["sassy"] = { Name = "move_m@sassy" },
	["sassy2"] = { Name = "move_f@sassy" },
	["scared"] = { Name = "move_f@scared" },
	["sexy"] = { Name = "move_f@sexy@a" },
	["shady"] = { Name = "move_m@shadyped@a" },
	["slow"] = { Name = "move_characters@jimmy@slow@" },
	["swagger"] = { Name = "move_m@swagger" },
	["tough"] = { Name = "move_m@tough_guy@" },
	["tough2"] = { Name = "move_f@tough_guy@" },
	["trash"] = { Name = "clipset@move@trash_fast_turn" },
	["trash2"] = { Name = "missfbi4prepp1_garbageman" },
	["trevor"] = { Name = "move_p_m_two" },
	["wide"] = { Name = "move_m@bag" },
	["crouch"] = { Name = "move_ped_crouched" },
}

Expressions = {
	{
		Name = "Normal",
		Icon = "sentiment_neutral",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_normal_1", Facial = true },
	},
	{
		Name = "Smug",
		Icon = "sentiment_neutral",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_smug_1", Facial = true },
	},
	{
		Name = "Happy",
		Icon = "insert_emoticon",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_happy_1", Facial = true },
	},
	{
		Name = "Excited",
		Icon = "insert_emoticon",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_excited_1", Facial = true },
	},
	{
		Name = "Shocked",
		Icon = "insert_emoticon",
		Anim = { Dict = "facials@gen_female@base", Name = "shocked_1", Facial = true },
	},
	{
		Name = "Injured",
		Icon = "sentiment_dissatisfied",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_injured_1", Facial = true },
	},
	{
		Name = "Stressed",
		Icon = "sentiment_dissatisfied",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_stressed_1", Facial = true },
	},
	{
		Name = "Sulk",
		Icon = "sentiment_dissatisfied",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_sulk_1", Facial = true },
	},
	{
		Name = "Sleeping",
		Icon = "bed",
		Anim = { Dict = "facials@gen_male@base", Name = "mood_sleeping_1", Facial = true },
	},
	{
		Name = "Dead",
		Icon = "sentiment_very_dissatisfied",
		Anim = { Dict = "facials@gen_male@base", Name = "dead_1", Facial = true },
	},
	{
		Name = "Electrocuted",
		Icon = "bolt",
		Anim = { Dict = "facials@gen_male@base", Name = "electrocuted_1", Facial = true },
	},
	{
		Name = "Focus",
		Icon = "priority_high",
		Anim = { Dict = "facials@gen_male@base", Name = "effort_1", Facial = true },
	},
}