Register("Spike Strips", {
	Placement = "Floor",
	Stackable = {
		Structure = false,
		Foundation = true,
		Block = false,
	},
	Model = {
		"p_ld_stinger_s",
	},
})

Register("ATM", {
	user = "Admin",
	NoDecay = true,
	Placement = "Floor",
	Stackable = {
		Structure = false,
		Foundation = true,
		Block = false,
	},
	Model = {
		"prop_atm_01",
	},
})

Register("Barricade", {
	user = "Mod",
	NoDecay = true,
	Placement = "Floor",
	Stackable = {
		Structure = false,
		Foundation = true,
		Block = false,
	},
	Model = {
		"ba_prop_battle_barrier_01c",
		"ba_prop_battle_barrier_02a",
		"p_barriercrash_01_s",
		"prop_air_barrier",
		"prop_barrier_wat_01a",
		"prop_barrier_wat_03a",
		"prop_barrier_wat_03b",
		"prop_barrier_wat_04a",
		"prop_barrier_wat_04b",
		"prop_barrier_wat_04c",
		"prop_barrier_work01a",
		"prop_barrier_work01b",
		"prop_barrier_work01c",
		"prop_barrier_work01d",
		"prop_barrier_work02a",
		"prop_barrier_work04a",
		"prop_barrier_work05",
		"prop_barrier_work06a",
		"prop_barrier_work06b",
		"prop_barriercrash_01",
		"prop_barriercrash_02",
		"prop_barriercrash_03",
		"prop_barriercrash_04",
		"prop_mc_conc_barrier_01",
		"prop_mp_barrier_01",
		"prop_mp_barrier_01b",
		"prop_mp_barrier_02",
		"prop_mp_barrier_02b",
		"prop_mp_conc_barrier_01",
		"prop_tyre_wall_01",
		"prop_tyre_wall_02",
		"prop_tyre_wall_03",
		"prop_tyre_wall_04",
		"prop_tyre_wall_05",
		"prop_offroad_tyres02",
		"prop_tyre_wall_01b",
		"prop_tyre_wall_02b",
		"prop_tyre_wall_03b",
		"stt_prop_tyre_wall_01",
		"stt_prop_tyre_wall_02",
		"stt_prop_tyre_wall_03",
		"stt_prop_tyre_wall_04",
		"stt_prop_tyre_wall_05",
		"stt_prop_tyre_wall_06",
		"stt_prop_tyre_wall_07",
		"stt_prop_tyre_wall_08",
		"stt_prop_tyre_wall_09",
		"stt_prop_tyre_wall_010",
		"stt_prop_tyre_wall_011",
		"stt_prop_tyre_wall_012",
		"stt_prop_tyre_wall_013",
		"stt_prop_tyre_wall_014",
		"stt_prop_tyre_wall_015",
		"stt_prop_tyre_wall_0l010",
		"stt_prop_tyre_wall_0l012",
		"stt_prop_tyre_wall_0l013",
		"stt_prop_tyre_wall_0l014",
		"stt_prop_tyre_wall_0l015",
		"stt_prop_tyre_wall_0l018",
		"stt_prop_tyre_wall_0l019",
		"stt_prop_tyre_wall_0l020",
	},
})

Register("Cone", {
	NoDecay = true,
	Placement = "Floor",
	Stackable = {
		Structure = false,
		Foundation = true,
		Block = false,
	},
	Model = {
		"prop_mp_cone_01",
		"prop_mp_cone_02",
		"prop_mp_cone_03",
		"prop_mp_cone_04",
		"prop_roadcone01a",
		"prop_roadcone01b",
		"prop_roadcone01c",
		"prop_roadcone02a",
		"prop_roadcone02b",
		"prop_roadcone02c",
	},
})

Register("Kitchen Knives", {
	Placement = "Floor",
	Stackable = {
		Structure = true,
		Foundation = true,
		Block = false,
	},
	Model = {
		"prop_knife_stand",
	},
})


