Citizen.CreateThread(function()
	-- Other stuff normally here, stripped for the sake of only scenario stuff.
	local SCENARIO_TYPES = {
		"PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON",
		"PROP_HUMAN_SEAT_ARMCHAIR",
		"PROP_HUMAN_SEAT_BENCH",
		"PROP_HUMAN_SEAT_BENCH_DRINK_BEER",
		"PROP_HUMAN_SEAT_BENCH_FOOD",
		"PROP_HUMAN_SEAT_CHAIR",
		"PROP_HUMAN_SEAT_CHAIR_UPRIGHT",
		"PROP_HUMAN_SEAT_DECKCHAIR",
		"PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON",
		"WORLD_DOG_BARKING_ROTTWEILER",
		"WORLD_DOG_BARKING_RETRIEVER",
		"WORLD_DOG_BARKING_SHEPHERD",
		"WORLD_DOG_SITTING_ROTTWEILER",
		"WORLD_DOG_SITTING_RETRIEVER",
		"WORLD_DOG_SITTING_SHEPHERD",
		"WORLD_DOG_BARKING_SMALL",
		"WORLD_DOG_SITTING_SMALL",
		"WORLD_HUMAN_BUM_FREEWAY",
		"WORLD_HUMAN_BUM_SLUMPED",
		"WORLD_HUMAN_BUM_STANDING",
		"WORLD_HUMAN_BUM_WASH",
		"WORLD_HUMAN_COP_IDLES",
		"WORLD_HUMAN_DRINKING",
		"WORLD_HUMAN_GUARD_PATROL",
		"WORLD_HUMAN_GUARD_STAND",
		"WORLD_HUMAN_GUARD_STAND_CASINO",
		"WORLD_HUMAN_GUARD_STAND_CLUBHOUSE",
		"WORLD_HUMAN_GUARD_STAND_FACILITY",
		"WORLD_HUMAN_GUARD_STAND_ARMY",
		"WORLD_HUMAN_HANG_OUT_STREET",
		"WORLD_HUMAN_LEANING",
		"WORLD_HUMAN_STAND_IMPATIENT",
		"WORLD_HUMAN_SEAT_STEPS",
		"WORLD_HUMAN_SEAT_WALL",
		"WORLD_HUMAN_SMOKING",
		"WORLD_HUMAN_SMOKING_POT",
		"WORLD_HUMAN_STAND_MOBILE",
		"WORLD_HUMAN_VALET",
		"WORLD_VEHICLE_AMBULANCE",
		"WORLD_VEHICLE_BICYCLE_MOUNTAIN",
		"WORLD_VEHICLE_BICYCLE_ROAD",
		"WORLD_VEHICLE_FIRE_TRUCK",
		"WORLD_VEHICLE_HELI_LIFEGUARD",
		"WORLD_VEHICLE_MILITARY_PLANES_BIG",
		"WORLD_VEHICLE_MILITARY_PLANES_SMALL",
		"WORLD_VEHICLE_POLICE_BIKE",
		"WORLD_VEHICLE_POLICE_CAR",
		"WORLD_VEHICLE_POLICE_NEXT_TO_CAR",
		"WORLD_VEHICLE_QUARRY",
		"WORLD_VEHICLE_SECURITY_CAR",
	}
	local SCENARIO_GROUPS = {
		2017590552, -- LSIA planes.
		2141866469, -- Sandy Shores planes.
		1409640232, -- Grapeseed planes.
		"ng_planes", -- Far up in the skies jets.
	}
	local SUPPRESSED_MODELS = {
		-- Aircrafts
		"BLIMP",
		"BLIMP2",
		"BUZZARD",
		"BUZZARD2",
		"FROGGER",
		"JET",
		"HYDRA",
		"LAZER",
		"LUXOR",
		"LUXOR2",
		"POLMAV",
		"SHAMAL",
		"SWIFT",
		"TITAN",
		-- Military
		"RHINO",
		-- Emergency
		"FIRETRUK",
		"AMBULANCE",
		-- Misc
		"AIRTUG",
		"RIPLEY",
		"TACO",
		"MONSTER",
		-- Super Cars
		"ADDER",
		"TURISMOR",
		"ZENTORNO",
		"JESTER",
	}

	while true do
		for _, sctyp in next, SCENARIO_TYPES do
			SetScenarioTypeEnabled(sctyp, false)
		end
		for _, scgrp in next, SCENARIO_GROUPS do
			SetScenarioGroupEnabled(scgrp, false)
		end
		for _, model in next, SUPPRESSED_MODELS do
			SetVehicleModelIsSuppressed(GetHashKey(model), true)
		end
		Wait(10000)
	end
end)
