Config = {
	GridSize = 1,
	MaxDistance = 5.0,
	Controls = {
		Place = 24,
		Cancel = 25,
		FineTune = 21,
		RotateR = 44,
		RotateL = 46,
		VariantR = 96,
		VariantL = 97,
	},
	Decorations = {
		["Table"] = {
			Placement = "Floor",
			Model = {
				"apa_mp_h_din_table_01",
				"apa_mp_h_din_table_04",
				"apa_mp_h_din_table_05",
				"apa_mp_h_din_table_06",
				"apa_mp_h_din_table_11",
				"apa_mp_h_yacht_coffee_table_01",
				"apa_mp_h_yacht_coffee_table_02",
				"apa_mp_h_yacht_side_table_01",
				"apa_mp_h_yacht_side_table_02",
				"ba_prop_int_edgy_table_01",
				"ba_prop_int_trad_table",
				"bkr_prop_fakeid_table",
				"bkr_prop_weed_table_01b",
				"ex_mp_h_din_table_01",
				"ex_mp_h_din_table_04",
				"ex_mp_h_din_table_05",
				"ex_mp_h_din_table_06",
				"ex_mp_h_din_table_11",
				"ex_mp_h_yacht_coffee_table_01",
				"ex_mp_h_yacht_coffee_table_02",
				"ex_prop_ex_console_table_01",
				"gr_dlc_gr_yacht_props_table_01",
				"gr_dlc_gr_yacht_props_table_02",
				"gr_dlc_gr_yacht_props_table_03",
				"hei_heist_din_table_01",
				"hei_heist_din_table_04",
				"hei_heist_din_table_06",
				"hei_heist_din_table_07",
				"hei_prop_yah_table_01",
				"hei_prop_yah_table_02",
				"hei_prop_yah_table_03",
				"prop_chateau_table_01",
				"prop_fbi3_coffee_table",
				"prop_patio_lounger1_table",
				"prop_picnictable_01",
				"prop_rub_table_01",
				"prop_rub_table_02",
				"prop_t_coffe_table",
				"prop_table_02",
				"prop_table_03",
				"prop_table_03b_cs",
				"prop_table_03b",
				"prop_table_04",
				"prop_table_05",
				"prop_table_06",
				"prop_table_07",
				"prop_table_08_chr",
				"prop_table_08",
				"prop_table_tennis",
				"prop_tablesmall_01",
				"prop_ven_market_table1",
				"v_ilev_liconftable_sml",
				"v_corp_cd_rectable",
				"v_corp_conftable",
				"v_corp_conftable2",
				"v_corp_conftable3",
				"v_res_m_dinetble",
				"v_corp_sidetable",
				"v_med_p_coffeetable",
				"v_res_fh_coftbldisp",
				"v_med_p_sidetable",
				"v_res_tre_bedsidetableb",
				"v_res_tre_bedsidetable",
				"v_res_m_sidetable",
			},
		},
		["Ceiling Light"] = {
			Rotation = vector3(180, 0, 0),
			Placement = "Ceiling",
			Model = {
				"apa_mp_h_lampbulb_multiple_a",
				{
					Name = "v_serv_ct_striplight",
					Offset = vector3(0, 0, -0.5),
				},
			},
		},
		["Painting"] = {
			Rotation = vector3(0, -90, -90),
			Placement = "Wall",
			Model = "ch_prop_vault_painting_01a",
		},
	},
}
