Config = {
	ParkedLockChance = 0.93,
	DrivingLockChance = 0.86,
	BreakWindowDamage = 5.0,
	EngineToggleCooldown = 1500,
	Hotwiring = {
		Durations = {
			[0] = 60000,
			[1] = 30000,
			[2] = 10000,
		},
		Action = {
			Duration = 0,
			Label = "Hotwiring...",
			UseWhileDead = false,
			CanCancel = true,
			Disarm = true,
			Anim = {
				Flag = 17,
				Dict = "veh@std@ds@base",
				Name = "hotwire",
				DisableMovement = true,
				DisableCarMovement = true,
			},
		},
	},
	Lockpicking = {
		Action = {
			Duration = 10000,
			Label = "Lockpicking...",
			UseWhileDead = false,
			CanCancel = true,
			Disarm = true,
			Anim = {
				Flag = 17,
				Dict = "weapons@first_person@aim_idle@p_m_zero@melee@small_wpn@crowbar@fidgets@a",
				Name = "fidget_low_loop",
				DisableMovement = true,
			},
		},
	},
	TakingKeysInIgnition = {
		Action = {
			Duration = 1000,
			Label = "Taking keys...",
			UseWhileDead = false,
			CanCancel = false,
			Disarm = false,
			-- Anim = {
			-- 	Flag = 16,
			-- 	Dict = "veh@std@ds@base",
			-- 	Name = "start_engine",
			-- 	DisableMovement = true,
			-- 	DisableCarMovement = true,
			-- },
		},
	},
	Locking = {
		Anim = {
			Flag = 48,
			Dict = "anim@mp_player_intmenu@key_fob@",
			Name = "fob_click",
			Duration = 1000,
			Props = {
				{ Model = "lr_prop_carkey_fob", Bone = 28422, Offset = { -0.02, -0.02, 0.02, 0.0, 10.0, 40.0 }},
			}
		},
	},
	Driving = {
		FuelBurnRate = 0.0001,
		OilBurnRate = 0.0000001,
	},
	Damage = {
		PartReflection = 0.2, -- How much parts take when body/engine are damaged.
		BodyDamageMult = 3.0,
		EngineDamageMult = 5.0,
		BodyToEngineDamageRatio = 0.8,
		BulletDamageMult = 0.5, -- Multiplied by body/engine damage mults.
		MeleeDamageMult = 0.4, -- Multiplied by body/engine damage mults.
		CriticalEvent = {
			MinDamage = 20.0,
			MaxDamage = 100.0,
			MinSpeed = 30.0 / 2.237,
			MaxSpeed = 140.0 / 2.237,
			OnRimChance = 0.25,
			TotaledCritChance = 0.2,
			TotaledChance = 0.8,
		},
		UndriveableEngineHealth = 100.0,
		AxleRate = 0.0000004,
		AxleModifier = 0.2,
		BrakeRate = 0.000001,
		BrakeModifier = 0.9,
		FuelInjector = {
			Rate = 0.0001,
			DriveModifier = 0.5,
			AddDrag = 0.5,
		},
		Electronics = {
			RollDamage = 0.00001, -- When the vehicle is spinning a lot.
			StallHealth = 0.3, -- Max health before stalling begins.
			StallTime = 500, -- In milliseconds, how long a vehicle stalls and the interval for the chance.
			StallChance = 0.05, -- Multiplied by health divided by stall health inverted.
			StallCooldown = 10000, -- How long before a stall can occur again.
		},
	},
	TiltClasses = {
		[8] = true,
		[13] = true,
		[15] = true,
		[16] = true,
	},
	DrivableClasses = {
		[0] = true, -- Compacts.
		[1] = true, -- Sedans.
		[2] = true, -- SUVs.
		[3] = true, -- Coupes.
		[4] = true, -- Muscle.
		[5] = true, -- Sports Classics.
		[6] = true, -- Sports.
		[7] = true, -- Super.
		[8] = true, -- Motorcycles.
		[9] = true, -- Off-road.
		[1] = true, -- Industrial.
		[1] = true, -- Utility.
		[1] = true, -- Vans.
		[1] = true, -- Service.
		[1] = true, -- Emergency.
		[1] = true, -- Military.
		[2] = true, -- Commercial.
	},
	Repairing = {
		Components = {
			{
				Name = "engine",
				Repair = "Engine",
				Offset = vector3(0, 0, -0.5),
				Mod = 11,
			},
			{
				Name = "engine",
				Repair = "Electronics",
				Offset = vector3(0, 0, -0.8)
			},
			{
				Name = "engine",
				Repair = "Transmission",
				Offset = vector3(-0.5, 0, -0.3),
				Mod = 13,
			},
			{
				Name = "engine",
				Repair = "Axle",
				Offset = vector3(0, 0, 0.3),
				Mod = 15,
			},
			{
				Name = "engine",
				Repair = "Fuel Injector",
				Offset = vector3(0.5, 0, -0.3),
			},
			{
				Name = "engine",
				Repair = "Radiator",
				Offset = vector3(0.0, 0.5, -0.1),
			},
			-- Fuel.
			{
				Name = "petroltank",
				Repair = "Fuel Tank",
				Offset = vector3(0, 0, 0),
			},
			{
				Name = "petroltank_l",
				Repair = "Fuel Tank",
				Offset = vector3(0, 0, -0.3),
			},
			{
				Name = "petroltank_r",
				Repair = "Fuel Tank",
				Offset = vector3(0, 0, -0.3),
			},
			{
				Name = "wheel_lr",
				Repair = "Fuel Tank",
				Offset = vector3(0, 0, -0.6),
				Condition = function(vehicle, bones)
					return bones["petroltank"] == nil and bones["petroltank_l"] == nil and bones["petroltank_r"] == nil
				end
			},
			-- Brakes.
			{
				Name = "wheel_lf",
				Repair = "Brakes",
				Offset = vector3(0.2, 0, 0),
				Condition = function(vehicle)
					return GetVehicleHandlingFloat(vehicle, "CHandlingData", "fBrakeBiasFront") > 0.4
				end,
				Mod = 12,
			},
			{
				Name = "wheel_rf",
				Repair = "Brakes",
				Offset = vector3(-0.2, 0, 0),
				Condition = function(vehicle)
					return GetVehicleHandlingFloat(vehicle, "CHandlingData", "fBrakeBiasFront") > 0.4
				end,
				Mod = 12,
			},
			{
				Name = "wheel_rr",
				Repair = "Brakes",
				Offset = vector3(-0.2, 0, 0),
				Condition = function(vehicle)
					return GetVehicleHandlingFloat(vehicle, "CHandlingData", "fBrakeBiasFront") < 0.6
				end,
				Mod = 12,
			},
			{
				Name = "wheel_lr",
				Repair = "Brakes",
				Offset = vector3(0.2, 0, 0),
				Condition = function(vehicle)
					return GetVehicleHandlingFloat(vehicle, "CHandlingData", "fBrakeBiasFront") < 0.6
				end,
				Mod = 12,
			},
		},
		Parts = {
			["Body"] = {
				BasicAmount = 300.0,
			},
			["Engine"] = {
				MaxBasic = 800.0,
				BasicAmount = 250.0,
				Item = "Iron Ingots",
				IsEngine = true,
			},
			["Fuel Tank"] = {
				MaxBasic = 900.0,
				BasicAmount = 250.0,
				Item = "Iron Ingots",
			},
			["Electronics"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_ElectronicsHealth",
				Item = "Copper Ingots",
			},
			["Transmission"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_TransmissionHealth",
				Item = "Iron Ingots",
			},
			["Axle"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_AxleHealth",
				Item = "Iron Ingots",
			},
			["Radiator"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_RadiatorHealth",
				Item = "Iron Ingots",
			},
			["Fuel Injector"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_FuelInjectorHealth",
				Item = "Iron Ingots",
			},
			["Brakes"] = {
				MaxBasic = 0.05,
				BasicAmount = 0.02,
				Decor = "Vehicle_BrakeHealth",
				Item = "Iron Ingots",
			},
		},
		Levels = {
			{ 0.83, "~g~New" },
			{ 0.67, "~g~Like New" },
			{ 0.5, "~y~Excellent" },
			{ 0.33, "~o~Good" },
			{ 0.17, "~o~Fair" },
			{ 0.0, "~r~Salvage" },
		},
		Action = {
			Anim = {
				Dict = "missmechanic",
				Name = "work2_base",
				Flag = 1,
				DisableMovement = true,
			},
			Label = "Repairing...",
			Duration = 8000,
			CanCancel = true,
			Disarm = true,
		},
		AdvancedAction = {
			Anim = {
				Dict = "missmechanic",
				Name = "work2_base",
				Flag = 1,
				DisableMovement = true,
			},
			Label = "Repairing...",
			Duration = 3000,
			CanCancel = true,
			Disarm = true,
		},
		MinDotProduct = 0.85,
		ActionDistance = 3.0,
		ViewDistance = 15.0,
		EngineDistance = 2.0,
	},
	HandlingFields = {
		"fMass",
		"fInitialDragCoeff",
		"fPercentSubmerged",
		"vecCentreOfMassOffset",
		"vecInertiaMultiplier",
		"fDriveBiasFront",
		-- "nInitialDriveGears",
		"fInitialDriveForce",
		"fDriveInertia",
		"fClutchChangeRateScaleUpShift",
		"fClutchChangeRateScaleDownShift",
		"fInitialDriveMaxFlatVel",
		"fBrakeForce",
		"fBrakeBiasFront",
		"fHandBrakeForce",
		"fSteeringLock",
		"fTractionCurveMax",
		"fTractionCurveMin",
		"fTractionCurveLateral",
		"fTractionSpringDeltaMax",
		"fLowSpeedTractionLossMult",
		"fCamberStiffnesss",
		"fTractionBiasFront",
		"fTractionLossMult",
		"fSuspensionForce",
		"fSuspensionCompDamp",
		"fSuspensionReboundDamp",
		"fSuspensionUpperLimit",
		"fSuspensionLowerLimit",
		"fSuspensionRaise",
		"fSuspensionBiasFront",
		"fAntiRollBarForce",
		"fAntiRollBarBiasFront",
		"fRollCentreHeightFront",
		"fRollCentreHeightRear",
		"fCollisionDamageMult",
		"fWeaponDamageMult",
		"fDeformationDamageMult",
		"fEngineDamageMult",
		"fPetrolTankVolume",
		"fOilVolume",
		"fSeatOffsetDistX",
		"fSeatOffsetDistY",
		"fSeatOffsetDistZ",
		"nMonetaryValue",
		-- "strModelFlags",
		-- "strHandlingFlags",
		-- "strDamageFlags",
		-- "AIHandling",
	},
	HandlingFuncs = {
		["f"] = { GetVehicleHandlingFloat, SetVehicleHandlingFloat },
		["n"] = { GetVehicleHandlingInt, SetVehicleHandlingInt },
		["v"] = { GetVehicleHandlingVector, SetVehicleHandlingVector },
	},
	Doors = {
		[0] = "door_dside_f",
		[1] = "door_pside_f",
		[2] = "door_dside_r",
		[3] = "door_pside_r",
		[4] = "bonnet",
		[5] = "boot",
		-- [6] = "back?",
		-- [7] = "back2?",
	},
	Bones = {
		["chassis"] = true,
		["chassis_lowlod"] = true,
		["chassis_dummy"] = true,
		["seat_dside_f"] = true,
		["seat_dside_r"] = true,
		["seat_dside_r1"] = true,
		["seat_dside_r2"] = true,
		["seat_dside_r3"] = true,
		["seat_dside_r4"] = true,
		["seat_dside_r5"] = true,
		["seat_dside_r6"] = true,
		["seat_dside_r7"] = true,
		["seat_pside_f"] = true,
		["seat_pside_r"] = true,
		["seat_pside_r1"] = true,
		["seat_pside_r2"] = true,
		["seat_pside_r3"] = true,
		["seat_pside_r4"] = true,
		["seat_pside_r5"] = true,
		["seat_pside_r6"] = true,
		["seat_pside_r7"] = true,
		["window_lf1"] = true,
		["window_lf2"] = true,
		["window_lf3"] = true,
		["window_rf1"] = true,
		["window_rf2"] = true,
		["window_rf3"] = true,
		["window_lr1"] = true,
		["window_lr2"] = true,
		["window_lr3"] = true,
		["window_rr1"] = true,
		["window_rr2"] = true,
		["window_rr3"] = true,
		["door_dside_f"] = true,
		["door_dside_r"] = true,
		["door_pside_f"] = true,
		["door_pside_r"] = true,
		["handle_dside_f"] = true,
		["handle_dside_r"] = true,
		["handle_pside_f"] = true,
		["handle_pside_r"] = true,
		["wheel_lf"] = true,
		["wheel_rf"] = true,
		["wheel_lm1"] = true,
		["wheel_rm1"] = true,
		["wheel_lm2"] = true,
		["wheel_rm2"] = true,
		["wheel_lm3"] = true,
		["wheel_rm3"] = true,
		["wheel_lr"] = true,
		["wheel_rr"] = true,
		["suspension_lf"] = true,
		["suspension_rf"] = true,
		["suspension_lm"] = true,
		["suspension_rm"] = true,
		["suspension_lr"] = true,
		["suspension_rr"] = true,
		["spring_rf"] = true,
		["spring_lf"] = true,
		["spring_rr"] = true,
		["spring_lr"] = true,
		["transmission_f"] = true,
		["transmission_m"] = true,
		["transmission_r"] = true,
		["hub_lf"] = true,
		["hub_rf"] = true,
		["hub_lm1"] = true,
		["hub_rm1"] = true,
		["hub_lm2"] = true,
		["hub_rm2"] = true,
		["hub_lm3"] = true,
		["hub_rm3"] = true,
		["hub_lr"] = true,
		["hub_rr"] = true,
		["windscreen"] = true,
		["windscreen_r"] = true,
		["window_lf"] = true,
		["window_rf"] = true,
		["window_lr"] = true,
		["window_rr"] = true,
		["window_lm"] = true,
		["window_rm"] = true,
		["bodyshell"] = true,
		["bumper_f"] = true,
		["bumper_r"] = true,
		["wing_rf"] = true,
		["wing_lf"] = true,
		["bonnet"] = true,
		["boot"] = true,
		["exhaust"] = true,
		["exhaust_2"] = true,
		["exhaust_3"] = true,
		["exhaust_4"] = true,
		["exhaust_5"] = true,
		["exhaust_6"] = true,
		["exhaust_7"] = true,
		["exhaust_8"] = true,
		["exhaust_9"] = true,
		["exhaust_10"] = true,
		["exhaust_11"] = true,
		["exhaust_12"] = true,
		["exhaust_13"] = true,
		["exhaust_14"] = true,
		["exhaust_15"] = true,
		["exhaust_16"] = true,
		["engine"] = true,
		["overheat"] = true,
		["overheat_2"] = true,
		["petrolcap"] = true,
		["petroltank"] = true,
		["petroltank_l"] = true,
		["petroltank_r"] = true,
		["steering"] = true,
		["hbgrip_l"] = true,
		["hbgrip_r"] = true,
		["headlight_l"] = true,
		["headlight_r"] = true,
		["taillight_l"] = true,
		["taillight_r"] = true,
		["indicator_lf"] = true,
		["indicator_rf"] = true,
		["indicator_lr"] = true,
		["indicator_rr"] = true,
		["brakelight_l"] = true,
		["brakelight_r"] = true,
		["brakelight_m"] = true,
		["reversinglight_l"] = true,
		["reversinglight_r"] = true,
		["extralight_1"] = true,
		["extralight_2"] = true,
		["extralight_3"] = true,
		["extralight_4"] = true,
		["numberplate"] = true,
		["interiorlight"] = true,
		["siren1"] = true,
		["siren2"] = true,
		["siren3"] = true,
		["siren4"] = true,
		["siren5"] = true,
		["siren6"] = true,
		["siren7"] = true,
		["siren8"] = true,
		["siren9"] = true,
		["siren10"] = true,
		["siren11"] = true,
		["siren12"] = true,
		["siren13"] = true,
		["siren14"] = true,
		["siren15"] = true,
		["siren16"] = true,
		["siren17"] = true,
		["siren18"] = true,
		["siren19"] = true,
		["siren20"] = true,
		["siren_glass1"] = true,
		["siren_glass2"] = true,
		["siren_glass3"] = true,
		["siren_glass4"] = true,
		["siren_glass5"] = true,
		["siren_glass6"] = true,
		["siren_glass7"] = true,
		["siren_glass8"] = true,
		["siren_glass9"] = true,
		["siren_glass10"] = true,
		["siren_glass11"] = true,
		["siren_glass12"] = true,
		["siren_glass13"] = true,
		["siren_glass14"] = true,
		["siren_glass15"] = true,
		["siren_glass16"] = true,
		["siren_glass17"] = true,
		["siren_glass18"] = true,
		["siren_glass19"] = true,
		["siren_glass20"] = true,
		["spoiler"] = true,
		["struts"] = true,
		["misc_a"] = true,
		["misc_b"] = true,
		["misc_c"] = true,
		["misc_d"] = true,
		["misc_e"] = true,
		["misc_f"] = true,
		["misc_g"] = true,
		["misc_h"] = true,
		["misc_i"] = true,
		["misc_j"] = true,
		["misc_k"] = true,
		["misc_l"] = true,
		["misc_m"] = true,
		["misc_n"] = true,
		["misc_o"] = true,
		["misc_p"] = true,
		["misc_q"] = true,
		["misc_r"] = true,
		["misc_s"] = true,
		["misc_t"] = true,
		["misc_u"] = true,
		["misc_v"] = true,
		["misc_w"] = true,
		["misc_x"] = true,
		["misc_y"] = true,
		["misc_z"] = true,
		["misc_1"] = true,
		["misc_2"] = true,
		["weapon_1a"] = true,
		["weapon_1b"] = true,
		["weapon_1c"] = true,
		["weapon_1d"] = true,
		["weapon_1a_rot"] = true,
		["weapon_1b_rot"] = true,
		["weapon_1c_rot"] = true,
		["weapon_1d_rot"] = true,
		["weapon_2a"] = true,
		["weapon_2b"] = true,
		["weapon_2c"] = true,
		["weapon_2d"] = true,
		["weapon_2a_rot"] = true,
		["weapon_2b_rot"] = true,
		["weapon_2c_rot"] = true,
		["weapon_2d_rot"] = true,
		["weapon_3a"] = true,
		["weapon_3b"] = true,
		["weapon_3c"] = true,
		["weapon_3d"] = true,
		["weapon_3a_rot"] = true,
		["weapon_3b_rot"] = true,
		["weapon_3c_rot"] = true,
		["weapon_3d_rot"] = true,
		["weapon_4a"] = true,
		["weapon_4b"] = true,
		["weapon_4c"] = true,
		["weapon_4d"] = true,
		["weapon_4a_rot"] = true,
		["weapon_4b_rot"] = true,
		["weapon_4c_rot"] = true,
		["weapon_4d_rot"] = true,
		["turret_1base"] = true,
		["turret_1barrel"] = true,
		["turret_2base"] = true,
		["turret_2barrel"] = true,
		["turret_3base"] = true,
		["turret_3barrel"] = true,
		["ammobelt"] = true,
		["searchlight_base"] = true,
		["searchlight_light"] = true,
		["attach_female"] = true,
		["roof"] = true,
		["roof2"] = true,
		["soft_1"] = true,
		["soft_2"] = true,
		["soft_3"] = true,
		["soft_4"] = true,
		["soft_5"] = true,
		["soft_6"] = true,
		["soft_7"] = true,
		["soft_8"] = true,
		["soft_9"] = true,
		["soft_10"] = true,
		["soft_11"] = true,
		["soft_12"] = true,
		["soft_13"] = true,
		["forks"] = true,
		["mast"] = true,
		["carriage"] = true,
		["fork_l"] = true,
		["fork_r"] = true,
		["forks_attach"] = true,
		["frame_1"] = true,
		["frame_2"] = true,
		["frame_3"] = true,
		["frame_pickup_1"] = true,
		["frame_pickup_2"] = true,
		["frame_pickup_3"] = true,
		["frame_pickup_4"] = true,
		["freight_cont"] = true,
		["freight_bogey"] = true,
		["freightgrain_slidedoor"] = true,
		["door_hatch_r"] = true,
		["door_hatch_l"] = true,
		["tow_arm"] = true,
		["tow_mount_a"] = true,
		["tow_mount_b"] = true,
		["tipper"] = true,
		["combine_reel"] = true,
		["combine_auger"] = true,
		["slipstream_l"] = true,
		["slipstream_r"] = true,
		["arm_1"] = true,
		["arm_2"] = true,
		["arm_3"] = true,
		["arm_4"] = true,
		["scoop"] = true,
		["boom"] = true,
		["stick"] = true,
		["bucket"] = true,
		["shovel_2"] = true,
		["shovel_3"] = true,
		["Lookat_UpprPiston_head"] = true,
		["Lookat_LowrPiston_boom"] = true,
		["Boom_Driver"] = true,
		["cutter_driver"] = true,
		["vehicle_blocker"] = true,
		["extra_1"] = true,
		["extra_2"] = true,
		["extra_3"] = true,
		["extra_4"] = true,
		["extra_5"] = true,
		["extra_6"] = true,
		["extra_7"] = true,
		["extra_8"] = true,
		["extra_9"] = true,
		["extra_ten"] = true,
		["extra_11"] = true,
		["extra_12"] = true,
		["break_extra_1"] = true,
		["break_extra_2"] = true,
		["break_extra_3"] = true,
		["break_extra_4"] = true,
		["break_extra_5"] = true,
		["break_extra_6"] = true,
		["break_extra_7"] = true,
		["break_extra_8"] = true,
		["break_extra_9"] = true,
		["break_extra_10"] = true,
		["mod_col_1"] = true,
		["mod_col_2"] = true,
		["mod_col_3"] = true,
		["mod_col_4"] = true,
		["mod_col_5"] = true,
		["handlebars"] = true,
		["forks_u"] = true,
		["forks_l"] = true,
		["wheel_f"] = true,
		["swingarm"] = true,
		["wheel_r"] = true,
		["crank"] = true,
		["pedal_r"] = true,
		["pedal_l"] = true,
		["static_prop"] = true,
		["moving_prop"] = true,
		["static_prop2"] = true,
		["moving_prop2"] = true,
		["rudder"] = true,
		["rudder2"] = true,
		["wheel_rf1_dummy"] = true,
		["wheel_rf2_dummy"] = true,
		["wheel_rf3_dummy"] = true,
		["wheel_rb1_dummy"] = true,
		["wheel_rb2_dummy"] = true,
		["wheel_rb3_dummy"] = true,
		["wheel_lf1_dummy"] = true,
		["wheel_lf2_dummy"] = true,
		["wheel_lf3_dummy"] = true,
		["wheel_lb1_dummy"] = true,
		["wheel_lb2_dummy"] = true,
		["wheel_lb3_dummy"] = true,
		["bogie_front"] = true,
		["bogie_rear"] = true,
		["rotor_main"] = true,
		["rotor_rear"] = true,
		["rotor_main_2"] = true,
		["rotor_rear_2"] = true,
		["elevators"] = true,
		["tail"] = true,
		["outriggers_l"] = true,
		["outriggers_r"] = true,
		["rope_attach_a"] = true,
		["rope_attach_b"] = true,
		["prop_1"] = true,
		["prop_2"] = true,
		["elevator_l"] = true,
		["elevator_r"] = true,
		["rudder_l"] = true,
		["rudder_r"] = true,
		["prop_3"] = true,
		["prop_4"] = true,
		["prop_5"] = true,
		["prop_6"] = true,
		["prop_7"] = true,
		["prop_8"] = true,
		["rudder_2"] = true,
		["aileron_l"] = true,
		["aileron_r"] = true,
		["airbrake_l"] = true,
		["airbrake_r"] = true,
		["wing_l"] = true,
		["wing_r"] = true,
		["wing_lr"] = true,
		["wing_rr"] = true,
		["engine_l"] = true,
		["engine_r"] = true,
		["nozzles_f"] = true,
		["nozzles_r"] = true,
		["afterburner"] = true,
		["wingtip_1"] = true,
		["wingtip_2"] = true,
		["gear_door_fl"] = true,
		["gear_door_fr"] = true,
		["gear_door_rl1"] = true,
		["gear_door_rr1"] = true,
		["gear_door_rl2"] = true,
		["gear_door_rr2"] = true,
		["gear_door_rml"] = true,
		["gear_door_rmr"] = true,
		["gear_f"] = true,
		["gear_rl"] = true,
		["gear_lm1"] = true,
		["gear_rr"] = true,
		["gear_rm1"] = true,
		["gear_rm"] = true,
		["prop_left"] = true,
		["prop_right"] = true,
		["legs"] = true,
		["attach_male"] = true,
		["draft_animal_attach_lr"] = true,
		["draft_animal_attach_rr"] = true,
		["draft_animal_attach_lm"] = true,
		["draft_animal_attach_rm"] = true,
		["draft_animal_attach_lf"] = true,
		["draft_animal_attach_rf"] = true,
		["wheelcover_l"] = true,
		["wheelcover_r"] = true,
		["barracks"] = true,
		["pontoon_l"] = true,
		["pontoon_r"] = true,
		["no_ped_col_step_l"] = true,
		["no_ped_col_strut_1_l"] = true,
		["no_ped_col_strut_2_l"] = true,
		["no_ped_col_step_r"] = true,
		["no_ped_col_strut_1_r"] = true,
		["no_ped_col_strut_2_r"] = true,
		["light_cover"] = true,
		["emissives"] = true,
		["neon_l"] = true,
		["neon_r"] = true,
		["neon_f"] = true,
		["neon_b"] = true,
		["dashglow"] = true,
		["doorlight_lf"] = true,
		["doorlight_rf"] = true,
		["doorlight_lr"] = true,
		["doorlight_rr"] = true,
		["unknown_id"] = true,
		["dials"] = true,
		["engineblock"] = true,
		["bobble_head"] = true,
		["bobble_base"] = true,
		["bobble_hand"] = true,
		["chassis_Control"] = true,
	},
	Refueling = {
		Anim = {
			Dict = "weapon@w_sp_jerrycan",
			Name = "fire",
			Flag = 49,
			DisableMovement = true,
		},
		TankDistnace = 2.0,
		PumpDistance = 2.5,
		Models = {
			[-164877493] = true,
			[-2007231801] = true,
			[-469694731] = true,
			[1339433404] = true,
			[1694452750] = true,
			[1933174915] = true,
			[-462817101] = true,
		},
		Bones = {
			{
				Name = "petroltank",
			},
			{
				Name = "petroltank_l",
			},
			{
				Name = "petroltank_r",
			},
			{
				Name = "wheel_lr",
				Offset = vector3(0.0, 0.0, -0.4),
			},
			{
				Name = "engine",
				Offset = vector3(0, 0, -0.5),
				Condition = function(vehicle, bones)
					return GetVehicleClass(vehicle) == 14
				end
			}
		}
	},
	Flipping = {
		MaxDistance = 3.0,
		Action  = {
			Anim = {
				Dict = "anim@arena@prize_wheel@male",
				Name = "idle_spinning",
				Flag = 1,
				DisableMovement = true,
			},
			Label = "Flipping...",
			Duration = 20000,
			UseWhileDead = false,
			CanCancel = true,
			Disarm = true,
		},
	},
	Towing = {
		Action  = {
			Anim = {
				Dict = "missexile3",
				Name = "ex03_dingy_search_case_base_michael",
				Flag = 48,
				DisableMovement = true,
			},
			Label = "Towing...",
			Duration = 4000,
			UseWhileDead = false,
			CanCancel = true,
			Disarm = true,
		},
		Beds = {
			[1353720154] = {
				Entry = vector3(0.0, -9.0, 0.0),
				Offset = vector3(0.0, -2.5, 1.0),
				Rot = vector3(0.0, 0.0, 0.0),
				Bone = 0,
			},
			[-777275802] = {
				Entry = vector3(0.0, -14.0, 0.0),
				Offset = vector3(0.0, 0.0, -0.5),
				Rot = vector3(0.0, 0.0, 0.0),
				Bone = 0,
			},
			[-1352468814] = {
				Entry = vector3(0.0, -10.0, 0.0),
				Offset = vector3(0.0, -1.0, 1.2),
				Rot = vector3(0.0, 0.0, 0.0),
				Bone = 0,
			},
		},
		Classes = {
			[0] = true, -- Compacts.
			[1] = true, -- Sedans.
			[2] = true, -- SUVs.
			[3] = true, -- Coupes.
			[4] = true, -- Muscle.
			[5] = true, -- Sports Classics.
			[6] = true, -- Sports.
			[7] = true, -- Super.
			[8] = true, -- Motorcycles.
			[9] = true, -- Off-road.
			[10] = true, -- Industrial.
			[11] = true, -- Utility.
			[12] = true, -- Vans.
			[13] = true, -- Cycles.
			[14] = false, -- Boats.
			[15] = false, -- Helicopters.
			[16] = false, -- Planes.
			[17] = false, -- Service.
			[18] = true, -- Emergency.
			[19] = false, -- Military.
			[20] = false, -- Commercial.
			[21] = false, -- Trains.
		},
		Blacklist = {

		},
		Whitelist = {
			["buzzard"] = true,
			["buzzard2"] = true,
			["frogger"] = true,
			["frogger2"] = true,
			["maverick"] = true,
			["polmav"] = true,
		},
		Distance = 5.0,
	},
	Upgrades = {
		Items = {
			{ Name = "Brakes", Max = 3, Mod = 12 },
			{ Name = "Engine", Max = 4, Mod = 11 },
			{ Name = "Suspension", Max = 4, Mod = 15 },
			{ Name = "Transmission", Max = 3, Mod = 13 },
		},
		Action = {
			Anim = {
				Dict = "missmechanic",
				Name = "work2_base",
				Flag = 49,
				DisableMovement = true,
			},
			Label = "Upgrading...",
			Duration = 15000,
			CanCancel = true,
			Disarm = true,
		},
	},
	TrafficLights = {
		[589548997] = true,
		[-945465914] = true,
		[1043035044] = true,
		[-655644382] = true,
		[865627822] = true,
		[-730685616] = true,
		[656557234] = true,
		[862871082] = true,
	},
}